---
params:
  dynamictitle: "module4_22"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 8)
cereal2 = pd.read_csv('cereal2.csv')
cereal2 = cereal2.loc[:,['name', 'mfr_type', 'type', 'calories', 'protein','fiber', 'fat',  'carbo',  'rating' ]].assign(hot=cereal2['type'] == 'Hot').drop(columns='type')
cereal = cereal2.assign(calories=cereal2['calories'].astype('str'))
```


type: slides


# Splitting a column

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## String Split 

```{python}
cereal
```
You may have noticed that one of our columns contains 2 variables. `mfr_type` is displaying both the manufacturer  (N, Q, etc.) and the cereal type (Cold, Hot). To convert this into tidier data we will need to split up this column into 2 separate ones, but how?

At the beginning of this Module, we were introduced to the verb `.split()` which split up a string into separate substrings. Pandas has a verb that similarly splits a column into separate ones. It's called `.str.split()`.
Let's test it out.

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

```{python}
cereal.head(2)
```

We need to isolate the column and make sure we are splitting on the correct separator. In this case, the column is `mfr_type` and the separator is `-`.   
It's important that we set `expand=True` to indicate that we want to split the sub strings into separate columns.
```{python}
new = cereal['mfr_type'].str.split('-', expand=True)
new 
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Great! We have 2 new columns. We will need to rename them and add them back to our original dataframe. 


```{python}
new = new.rename(columns = {0:'mfr', 1: 'type'})
new
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We can then use assign to add the columns from the `new` dataframe into the original `cereal` one: 
```{python}
cereal = cereal.assign(mfr=new['mfr'],
                       type=new['type'])
cereal
```



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

You may be wondering **What happens if we don't use `expand=False`**? Well, let's take a look!

```{python}
new = cereal['mfr_type'].str.split('-', expand=False)
new 
```
Our output is now a Pandas Series data type with a list containing both column values as the Series values.

```{python}
type(new)
```

This not ideal for splitting up values in a column.  

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s practice what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />