---
params:
  dynamictitle: "module4_22"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 8)
cereal2 = pd.read_csv('cereal2.csv')
cereal2 = cereal2.loc[:,['name', 'mfr_type', 'type', 'calories', 'protein','fiber', 'fat',  'carbo',  'rating' ]].assign(hot=cereal2['type'] == 'Hot').drop(columns='type')
cereal_amended = cereal2.assign(calories=cereal2['calories'].astype('str'))
```


type: slides


# Splitting a column

Notes: 

<br>

---

## String Split 

```{python}
cereal_amended
```



Notes: 

Here is a new cereal dataframe. 

You'll notice that our column `mfr_type` contains two variables.

It is displaying both the manufacturer (N, Q, etc.) of the cereal and the cereal type (Cold, Hot). 

To convert this into tidier data, we will need to split up this column into two separate columns, but how?



---

```{python}
cereal_amended.head(5)
```


```{python}
new = cereal_amended['mfr_type'].str.split('-', expand=True)
new 
```

Notes: 

At the beginning of this Module, we were introduced to the verb `.split()` which split up a string into separate substrings. 

Pandas has a verb that similarly splits a column into separate ones. It's called `.str.split()`.

Let's test it out.

First, we need to grab the column and make sure we are splitting on the correct separator. 

In this case, the column is `mfr_type`, and the separator is `-`.   

It's important that we set `expand=True` to indicate that we want to split the substrings into separate columns.

As you can see from the result, we now have two new columns.

---

```{python}
new.head()
```

```{python}
new = new.rename(columns = {0:'mfr', 1: 'type'})
new.head()
```


Notes: 

We will need to rename them before we add them back to our original dataframe. 

---




```{python}
cereal = cereal_amended.assign(mfr=new['mfr'],
                       type=new['type'])
cereal
```



Notes: 

We can then use `.assign()` to add the columns from the `new` dataframe into the original `cereal` one.

Now we can see our new columns at the end of our cereal dataframe.

---

```{python}
new = cereal_amended['mfr_type'].str.split('-', expand=False)
new 
```


```{python}
type(new)
```



Notes:

You may be wondering **What happens if we use `expand=False` instead of `expand=True`**? 

Well, let's take a look!

Our output is now a Pandas Series data type with a list containing both column values as the Series values.

This makes it a little harder to add to the dataframe as separate columns. 

This not ideal for splitting up values in a column.  

---

# Let’s apply what we learned!

Notes: 

<br>