---
params:
  dynamictitle: "module4_22"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 10)
cereal2 = pd.read_csv('cereal2.csv')
cereal2 = cereal2.loc[:,['name', 'mfr_type', 'type', 'calories', 'protein','fiber', 'fat',  'carbo',  'rating' ]].assign(hot=cereal2['type'] == 'Hot').drop(columns='type')
cereal = cereal2.assign(calories=cereal2['calories'].astype('str'))
```


type: slides


# Operations with Columns

Notes: 

<br>

---



```{python}
cereal
```


Notes: 

We've just learned what Python values work with certain operations but what about dataframes?   

Let's take a look at our cereal dataframe once more.

---

```{python}
cereal.dtypes
```

```{python}
cereal.describe()
```

Notes: 

It's always a good idea to see what column types we have before operating on them, since they may not be of the type we expect. 

In this case, we discover that the `calories` column is of dtype `object` which isn't the `int64` category we expected. This can happen sometimes when reading in data - pandas doesn't always correctly guess what the type of a column should be. 

Since `calories` is not a numerical type, it will not show up in our summary statistics if we call `.describe()`:

---



```{python}
cereal['calories'].sum()
```

```{python}
cereal['calories'].astype('int')
```

Notes: 

If we attempt to sum the column, we get a concatenation of the column because the values are being treated as strings.

We saw earlier that when we add strings, they concatenate together. 

To go forward with any analysis, we are going to have to convert this column to a numeric type.

Luckily, there is an easy way to do it using the verb `.astype()`.

---


```{python}
cereal = cereal.assign(calories=cereal['calories'].astype('int'))

```


```{python}
cereal.dtypes
```



Notes: 

We can now use the verb `.assign()` to add the casted column back to the `cereal` dataframe. By using the same name `calories` we overwrite the previous column, but now as dtype `int`.

Great, it looks like we are back on track. 

---

```{python}
cereal.head(5)
```




```{python}
cereal['calories'].sum()
```

Notes: 

If we take the sum of the column now, we get the actual sum.

---

## object columns

```python 
cereal['mfr_type'].mean()
```

```out
TypeError: Could not convert N-ColdQ-ColdK-ColdK-ColdR-ColdG-ColdK-ColdG-ColdR-ColdP-ColdQ-ColdG-ColdG-ColdG-ColdG-ColdR-ColdK-ColdK-ColdG-ColdK-ColdN-HotK-ColdG-ColdR-ColdK-ColdK-ColdK-ColdP-ColdK-ColdP-ColdP-ColdG-ColdP-ColdP-ColdP-ColdQ-ColdG-ColdP-ColdK-ColdK-ColdG-ColdQ-ColdG-ColdA-HotR-ColdR-ColdK-ColdG-ColdK-ColdK-ColdK-ColdG-ColdP-ColdK-ColdQ-ColdQ-ColdQ-ColdQ-HotK-ColdG-ColdK-ColdR-ColdK-ColdN-ColdN-ColdN-ColdK-ColdK-ColdN-ColdG-ColdG-ColdG-ColdG-ColdG-ColdR-ColdG-ColdG-Cold to numeric

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 11459, in stat_func
    return self._reduce(
```

```{python}
cereal['mfr_type'].sum()
```

Notes: 

What happens if we try to take summary statistics of some of the other columns?

Yikes! let's not take the mean of columns of dtype `object`. 

As we saw before, taking a `.sum()` of a column concatenates the values together.

---

## Bool


```{python}
cereal['hot'].mean()
```

Notes:

What about the column of type `bool`? 

Since Booleans are cast to 0 and 1 for `True` and `False` values respectively, we can take the sum of a column to obtain the total number of `True` values.

`.mean()` works by suming up all the values and divides them by the total number of rows. 
In the case where the column is of dtype `bool`, since `True` has a value of 1 and `False` has a value of 0, the mean is calculated as the total number of `True` values divided by the total number of `True` and `False` values. In other words, this gives you the fraction of cases that are `True`. 


---

## Axis Argument 



```{python}
cereal.head(3)
```



```{python}
cereal.loc[:, 'protein': 'carbo'].sum(axis=1)
```



Notes: 

We are quite familiar with taking the mean and sum of entire columns now but there are times where we want the mean or sum of the values in a ***row***.  

Perhaps we wanted the total grams of `protein`,`fiber`,`fat` and `carbo` for each cereal?

Remember when we discussed the argument `axis` in Module 3? 

We can use it in our operations as well. 

`axis=1`  refers to the calculation being done for each row, across multiple columns, whereas `axis=0` (which is the default for aggregation verbs) refers to the calculation for each column, across multiple rows.




---

```{python}
cereal.loc[:, 'protein': 'carbo'].sum(axis=1)
```



```{python}
cereal = cereal.assign(total_pffc=cereal.loc[:, 'protein': 'carbo'].sum(axis=1))
cereal.head()
```



Notes: 

Although this produces the totals, we may want the result as an additional column in the dataframe.

That means we will have to combine it with `.assign()`. 

Here we add it as a column named `total_pffc` into the cereal dataframe. 

This syntax works for calculating the mean over multiple columns too. 

---

# Let’s apple what we learned!

Notes: 

<br>