---
params:
  dynamictitle: "module4_18"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)
cereal = pd.read_csv('cereal.csv')
```


type: slides


# Python operations 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We have already been a witness to a few of Python's arithmetic operators, but there are a few on this list that you have to to see:   
  
| Operator | Description |  
| :---:|:---:|  
| `+` | addition |  
| `-` | subtraction |  
| `*` | multiplication |  
| `/` | division |  
| `**` | exponentiation |   
| `//` | integer division |  
| `%`  | modulo |  


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's apply these to the Python types we have learned and observe the results.

## Numeric Operations 

These operators act as expected on numeric types: 

And `int` plus a `float` results in a `float`: 

```{python}
6 + 5.7
```

And the subtraction of 2 values of type `int` results with a type `int`:
```{python}
15 - 7
```

integer division will give the result of division rounded down to the nearest whole number
```{python}
15//2
```

The modulo operation will output with the remainder of the division. 
```{python}
15%2
```



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Bool 

These operations work as expected with numeric values but let's put on concentration on what happens with the other data types and structures. 
What happens when we try to add up `bool` values? 

```{python}
True + True 
```

```{python}
True * 4
```

```{python}
False * 2 + True
```

```{python}
True % 4
```

`True` values can undergo operations under the pretense that it acts as a value of `1` and False as a value of `0`. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Str

Strings react rather interestingly with the addition operator.  
For instance, when we add strings we add the sequence from one end to the other: 

```{python}
'The monster under my bed' + ' is named Mike' 
```

But we cannot multiply, divide or subtract them. 

```{python error=TRUE}
'The monster under my bed' - ' is named Mike' 
```
```{python error=TRUE}
'The monster under my bed' / ' is named Mike' 
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We saw that we can operate on `float` and `int` values together but what about `str` and numeric values? 

```{python error=TRUE}
'The monster under my bed' + 1200
```
That does not work, however, if we transform the numeric to a string, we can concatenate the two together: 

```{python}
'The monster under my bed' + str(1200)
```

How about with other data structure like **lists**, **tuples** and **dictionaries**?


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## List 

If we add lists, similarly to strings, the elements are combine to create a single list containing the elements of both lists. 
```{python}
list1 = [1, 2.0, 3, 4.5] + ['nine', 'ten', 'eleven', 'twelve']
```
We can add, but other operators are not supportive. 
```{python error=TRUE}
[1, 2.0, 3, 4.5] * [5, 6, 7, 8]
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---


We can sum up the elements in a list if they are numeric:
```{python error=TRUE}
sum([1, 2.0, 3, 4.5])
```

But not `str` elements.     
```{python error=TRUE}
sum(['nine', 'ten', 'eleven', 'twelve'])
```

Can we add strings and lists? 

```{python error=TRUE}
'The monster under my bed' + [1, 2.0, 3, 4.5]
```

Unfortunately not. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Tuples 

Tuples act in a much similar way as lists:

```{python}
tuple1 =(1, 2, 3, 4)
tuple2 = (5, 6, 7, 8)
```

We can only use the addition operator and the two tuples are combined end to end. 
```{python}
tuple1 + tuple2
```


## Dictionaries 

Unfortunately dictionaries cannot be operated on like `lists` and `tuples`: 

```{python}
dictionary1 = {1: 'one', 2: 'two'}
dictionary2 = {3: 'three', 4: 'four'}
```

```{python error=TRUE}
dictionary1 + dictionary2
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Boolean Operators 

When we've filtered our data we've seen different boolean operators however we have yet to see all that is available.

|Operator    |Description|
|:------:|:--------------|
|`x == y`|    is x equal to y?|
|`x != y`|    is x not equal to y?|
|`x > y` |    is x greater than y?|
|`x >= y`|    is x greater than or equal to y?|
|`x < y` |    is x less than y?|
|`x <= y`|    is x less than or equal to y?|
|`x is y`|    is x the same object as y?|
|`x and y` |     are x and y both true? |
|`x or y`    | is at least one of x and y true?|
|`not x`    | is x false?|

Let's explores these a bit more.


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's start with 2 base statements: 
```{python}
'dogs' != 'cats'
```

```{python}
6 > 7
```

We can combine them to explore `and` `or` and `not` operators. 
```{python}
(6 > 7) and ('dogs' != 'cats')
```
Since both statements are not true, the "and" statement is False.


```{python}
(6 > 7) or ('dogs' != 'cats')
```
Since one statement is true the combine "or" statement is True. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We know that `(6 > 7) ` is False so a `not` operator gives us a True value because it confirms the fact the statement is False. 
```{python}
not (6 > 7) 
```

We know `('dogs' != 'cats')` is True:
```{python}
not  ('dogs' != 'cats')
```
Seeing if the statement is False will result in a False statement since ` ('dogs' != 'cats')` is True. 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

How can we translate this to dataframes? Have you ever wondered why we can do summary statistics on some columns and not others? We are going to explore this in the next section. 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s practice what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />