---
params:
  dynamictitle: "module7_01"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3")
#use_python("/usr/local/bin/python3", required=T)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
import altair as alt
from altair_saver import save
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)
cereal = pd.read_csv('cereal.csv')
```


type: slides


# Importing Python Libraries

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

All the way back in Module 1, we learned how to import the `pandas` package for dataframe wrangling and `altair` to visualize our data with plots. 

We imported these packages because basic Python does not have all the built-in tools that we need to accomplish what we what hence, we import other tools into our environment. 

To import a package we can do the following:

```{python}
import pandas
```

This now lets us use functions that reside in the `pandas` package such as `read_csv()`. We need to specify the package name (`pandas`) and then the function (`read_csv()`):

```{python}
pandas.read_csv('cereal.csv').head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

For efficiency, for the majority of this course we have been importing our packages by assigning them a shorter condensed name.
For example, in the assignments and practice exercises, we have been importing `pandas` and `altair` with names such as `pd` and `alt`:

```{python}
import pandas as pd 
import altair as alt
```

now when we call functions from either of these packages we only type the short form we assigned to the package name, in this case `pd`: 

```{python}
pd.read_csv('cereal.csv').head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We can also import a single function from a package using the keyword `from`. If we only wanted the `read_csv()` function from the `pandas` package, we could do the following: 

```{python}
from pandas import read_csv
```

```{python}
read_csv('cereal.csv').head()
```
This mostly helps if we only have a single function we wish to use instead of importing the entire package. 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

This is all fun and dandy but how do we import functions we've made that are located in another file? We want to reuse code to adhere to the DRY principle, what is our next step? 

This question will be answered in the screencast and notes of the next section. 



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s practice what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />