---
params:
  dynamictitle: "module8_19"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module8/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3")
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)
cereal = pd.read_csv('cereal.csv')
cycling = pd.read_csv('cycling_data.csv')


```


type: slides

# Introduction to Working with Strings

Notes: Script here
<html>
<audio controls>
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Although we have already introduced you to strings to a certain degree, processing and working with this data type is an area that will require a substantial amount of learning. 

In this course, we will only scratch the surface when it comes to strings. That being said, we do hope to provide you with an adequate foundation in string processing. 

Notes: Script here
<html>
<audio controls >
  <source src="/module0/511_module0.mp3" />
</audio></html>

---

## Recap 

Let's first remind ourselves of some of the methods we've already learned such as:

- `.upper()`
- `.lower()` 
- `.uppercase()`
- `.count()`
- `.split()` 

When we work with just a general string, we can just use the function on the end of the object name. 
For example, if our string object name was `instrument`:

```{python}
instrument = 'Violin'
instrument
```

We could convert to all uppercase characters with: 
```{python}
instrument.upper()
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Convert the string to lowercase:

```{python}
instrument.lower()
```

Count the number of occurrences of the letter "i": 
```{python}
instrument.count('i')
```

And split a string on a specified character (in this case "i"): 
```{python}
instrument.split('i')
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Processing String Columns 


The only problem is that when we work with data, we will be applying these transformations, not to a single string, but to a whole column of them. 

We saw back in Module 4 that string data is represented in a pandas dataframe using the dtype `object`. This is the default dtype given to columns that have a mix of different data types or if pandas cannot identify the column as any other dtype. 

Remember when we discussed datetimes columns and we applied time functions to a whole column by adding `.dt` before the function? 

We can use that same syntax style when applying string transformations to entire columns but this time using `.str`.

Let's bring back our `cycling` dataframe to demonstrate:

```{python}
cycling.head()
```

Notes: Script here
<html>
<audio controls  >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Perhaps we wanted the entire `Comments` column in upper case. We can use `.assign()` and `.upper` paired with `.str` to transform the column.

```{python}
upper_cycle = cycling.assign(Comments = cycling['Comments'].str.upper())
upper_cycle.head()
```
Not too shabby! 

How about a new column that contains the number of times "RAIN" is counted in `upper_cycle`: 

```{python}
rain_cycle = upper_cycle.assign(Rain = upper_cycle['Comments'].str.count('RAIN'))
rain_cycle.head()
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We've also seen this syntax when we used `str.split()` in Module 4 when we learned about splitting our columns:

```{python}
upper_cycle['Comments'].str.split(expand=True)
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Another operation that we've lightly touched on is contatenation of  strings. For instance when we add 2 strings together: 

```{python}
"My favourite colour" + "is Blue"
```

This can be implemented in dataframes too by concatenating 2 columns to create a new one:

```{python}
combined_cycle = cycling.assign(Distance_str = cycling['Distance'].astype('str') + ' km')
combined_cycle.head()
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

A new function we haven't discussed but is quite similar to `.upper()` and `.lower()` is`.capitalize()` which capitalizes the first word of the string:

```{python}
cap_cycle = cycling.assign(Comments = cycling['Comments'].str.capitalize())
cap_cycle.head()
```
Another is `.title()`, which capitalizes the first letter of every word in a string:

```{python}
cap_cycle = cycling.assign(Comments = cycling['Comments'].str.title())
cap_cycle.head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

One function that might not seem that pertinent but is extremely useful is <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.strip.html" target="_blank">`.strip()` </a>.

`strip()` removes characters starting or ending a string, with the default being spaces. 

For Example:

To us, reading "Sunshine" and " Sunshine " are the same thing, but to Python, they are quite different because of the blank space surrounding it. 
```{python}
"Sunshine" == " Sunshine "
```

The blank space on either side of a string often needs to be removed depending on the analysis. 
We can remove them in the example above using `strip()`:

```{python}
string1 = " Sunshine " 
new_string1 = string1.strip()
new_string1
```
```{python}
"Sunshine" == new_string1
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

This can be especially frustrating when we are trying to filter dataframes.

Let's try to filter our data to find rows where the value for the `Comments` column is "Rain". 
```{python}
cycling.head()
```
We can see that index 0 should be filtered out but we get the following:

```{python}
cycling[cycling['Comments'] == 'Rain']
```

No rows are outputted. That's because there is a blank space following "Rain". 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---


Let's now strip our column using `.strip()` and assigning the changes to the `Comments` column of a dataframe named `stripped_cycling`. Since we are using `.strip()` with a dataframe column we have to add `.str`.

```{python}
stripped_cycling = cycling.assign(Comments = cycling['Comments'].str.strip())
stripped_cycling.head()
```
And what happens now when we filter on rain on our new `stripped_cycling` dataframe:

```{python}
stripped_cycling[stripped_cycling['Comments'] == 'Rain']
```
Ahh that's much better! 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We are not limited to stripping the values of white space. We can also strip any other character. Let's try punctuation!

```{python}
stripped_cycling.tail(5)
```
We can see that index 30 has a value of `Feeling good after a holiday break!` in the `Comments` column. 
After using `str.strip('!')` we can see that it's no loger has the  exclamation mark! 

```{python}
stripped_cycling['Comments'].str.strip("!").tail()
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s practice what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
