project:
  type: website
  title: "Programming in Python for Data Science"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome to Programming in Python for Data Science**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-programming_in_python_for_data_science.qmd
          - text: '&nbsp;&nbsp; 1.1. Prerequisite confirmation'
            href: modules/module0/module0-02-are_you_ready.qmd
      - section: "**M1. Python & Pandas - An Unexpected Friendship**"
        contents:
          - href: modules/module1/module1-00-module_learning_outcomes.qmd
          - href: modules/module1/module1-01-introduction_to_dataframes.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-describing_a_dataframe.qmd
          - href: modules/module1/module1-03-introduction_to_pandas.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module1/module1-04-definitions.qmd
          - href: modules/module1/module1-07-slicing_with_pandas_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module1/module1-08-slicing_and_dicing_practice.qmd
          - href: modules/module1/module1-11-slicing_columns_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module1/module1-12-slicing_columns_only.qmd
          - href: modules/module1/module1-13-selecting_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module1/module1-14-rearraging_columns_and_rows.qmd
          - href: modules/module1/module1-16-obtaining_dataframe_values.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module1/module1-17-practicing_selecting_values.qmd
          - href: modules/module1/module1-18-selecting_a_single_column.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module1/module1-19-practicing_selecting.qmd
          - href: modules/module1/module1-20-slicing_and_selecting_using_df.iloc[].qmd
          - text: '&nbsp;&nbsp; 8.1. Exercises'
            href: modules/module1/module1-21-practicing_slicing_and_selecting_using_index_position.qmd
          - href: modules/module1/module1-24-sorting_dataframes.qmd
          - text: '&nbsp;&nbsp; 9.1. Exercises'
            href: modules/module1/module1-25-practice_sorting.qmd
          - href: modules/module1/module1-26-summary_statistics.qmd
          - text: '&nbsp;&nbsp; 10.1. Exercises'
            href: modules/module1/module1-27-fruit_bowl_statistics.qmd
          - href: modules/module1/module1-29-frequency_tables_and_writing_csvs.qmd
          - text: '&nbsp;&nbsp; 11.1. Exercises'
            href: modules/module1/module1-30-practicing_frequency_tables.qmd
          - href: modules/module1/module1-31-quick_viz_with_altair.qmd
          - text: '&nbsp;&nbsp; 12.1. Exercises'
            href: modules/module1/module1-32-practicing_bar_charts.qmd
          - href: modules/module1/module1-34-what_did_we_just_learn.qmd
      - section: "**M2. Not So Scary Wrangling (Table Manipulation and Chaining)**"
        contents:
          - href: modules/module2/module2-00-module_learning_outcomes.qmd
          - href: modules/module2/module2-01-reading_in_different_file_types.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module2/module2-02-delimiter.qmd
          - href: modules/module2/module2-06-arguments_for_reading_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module2/module2-07-name_that_argument.qmd
          - href: modules/module2/module2-09-column_renaming_and_dropping.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module2/module2-10-column_editing_questions.qmd
          - href: modules/module2/module2-13-column_arithmetic_and_creation.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module2/module2-14-column_arithmetic_questions.qmd
          - href: modules/module2/module2-16-data_filtering.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module2/module2-17-filtering_question.qmd
          - href: modules/module2/module2-20-conditional_value_replacement.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module2/module2-21-practice_replacing_values.qmd
          - href: modules/module2/module2-22-chaining_notation.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module2/module2-23-chaining_true_false.qmd
          - href: modules/module2/module2-25-grouping_and_aggregating.qmd
          - text: '&nbsp;&nbsp; 8.1. Exercises'
            href: modules/module2/module2-26-fruit_salad_grouping_and_aggregating.qmd
          - href: modules/module2/module2-29-plotting_with_altair.qmd
          - text: '&nbsp;&nbsp; 9.1. Exercises'
            href: modules/module2/module2-30-plotting_a_groupby_object.qmd
          - href: modules/module2/module2-31-what_did_we_just_learn.qmd
      - section: "**M3. Tidy Data and Joining Dataframes**"
        contents:
          - href: modules/module3/module3-00-module_learning_outcomes.qmd
          - href: modules/module3/module3-01-what_is_tidy_data.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module3/module3-02-tidy_data_questions.qmd
          - href: modules/module3/module3-05-statistical_questions_and_tidy_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module3/module3-06-which_is_tidy.qmd
          - href: modules/module3/module3-08-reshaping_with_pivot.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-09-pivoting_questions.qmd
          - href: modules/module3/module3-11-reshaping_with_pivot_table.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module3/module3-12-pivot_table_questions.qmd
          - href: modules/module3/module3-14-reshaping_with_melt.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module3/module3-15-melting_questions.qmd
          - href: modules/module3/module3-17-concatenation.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module3/module3-18-concat_questions.qmd
          - href: modules/module3/module3-21-joining_dataframes_using_merge.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module3/module3-22-merge_questions.qmd
          - href: modules/module3/module3-25-what_did_we_just_learn.qmd
      - section: "**M4. Python Without the \"Eek\" (Basic Python)**"
        contents:
          - href: modules/module4/module4-00-module_learning_outcomes.qmd
          - href: modules/module4/module4-01-python_data_types.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module4/module4-02-name_that_data_type.qmd
          - href: modules/module4/module4-05-python_data_structures:_lists_tuples_and_sets.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module4/module4-06-name_that_data_structure.qmd
          - href: modules/module4/module4-10-python_data_structures:_dictionaries.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module4/module4-11-dictionary_questions.qmd
          - href: modules/module4/module4-14-dataframes_series_and_column_dtypes.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module4/module4-15-name_that_type_dtype.qmd
          - href: modules/module4/module4-18-python_operations.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module4/module4-19-output_or_error_with_operations.qmd
          - href: modules/module4/module4-21-operations_with_columns.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module4/module4-22-whats_that_output_with_column_operations.qmd
          - href: modules/module4/module4-23-splitting_a_column.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module4/module4-24-practice_operations_with_dataframe_columns.qmd
          - href: modules/module4/module4-25-what_did_we_just_learn.qmd
      - section: "**Module 5: Making Choices and Repeating Iterations**"
        contents:
          - href: modules/module5/module5-00-module_learning_outcomes.qmd
          - href: modules/module5/module5-01-making_choices_with_conditional_statements.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module5/module5-02-quick_questions_with_conditionals.qmd
          - href: modules/module5/module5-06-repeated_iterations_(loops).qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module5/module5-07-repeated_iterations_questions.qmd
          - href: modules/module5/module5-09-range_dictionaries_and_comprehensions.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module5/module5-10-range_questions.qmd
          - href: modules/module5/module5-13-nested_loops.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module5/module5-14-nested_loop_questions.qmd
          - href: modules/module5/module5-16-repeated_iterations_with_conditions.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module5/module5-17-conditional_loop_questions.qmd
          - href: modules/module5/module5-19-functions.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module5/module5-20-function_questions.qmd
          - href: modules/module5/module5-23-what_did_we_just_learn.qmd
      - section: "**Module 6: Functions Fundamentals and Best Practices**"
        contents:
          - href: modules/module6/module6-00-module_learning_outcomes.qmd
          - href: modules/module6/module6-01-dry_revisited_and_function_fundamentals.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module6/module6-02-questions_on_scoping.qmd
          - href: modules/module6/module6-05-default_arguments.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module6/module6-06-will_it_output.qmd
          - href: modules/module6/module6-09-function_docstrings.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module6/module6-10-docstring_questions.qmd
          - href: modules/module6/module6-13-defensive_programming_using_exceptions.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module6/module6-14-exceptions.qmd
          - href: modules/module6/module6-17-unit_tests.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module6/module6-18-assert_questions.qmd
          - href: modules/module6/module6-22-good_function_design_choices.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module6/module6-23-function_design_questions.qmd
          - href: modules/module6/module6-26-what_did_we_just_learn.qmd
      - section: "**Module 7: Importing Files and the Coding Style Guide**"
        contents:
          - href: modules/module7/module7-00-module_learning_outcomes.qmd
          - href: modules/module7/module7-01-importing_python_libraries.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module7/module7-02-importing_packages.qmd
          - href: modules/module7/module7-05-working_with_other_files.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module7/module7-06-importin_your_own_functions_quesitons.qmd
          - href: modules/module7/module7-08-testing_your_own_functions_with_pytest.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module7/module7-09-using_pytest_questions.qmd
          - href: modules/module7/module7-12-automatic_style_formatters.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module7/module7-13-flake8_and_black.qmd
          - href: modules/module7/module7-15-formatting_that_can't_be_fixed_automatically.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module7/module7-16-writing_useful_comments.qmd
          - href: modules/module7/module7-18-the_python_debugger.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module7/module7-19-using_the_python_debugger.qmd
          - href: modules/module7/module7-20-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true
