project:
  type: website
  title: "Programming in Python for Data Science"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M2. Not So Scary Wrangling (Table Manipulation and Chaining)**"
        contents:
          - href: modules/module2/module2-00-module_learning_outcomes.qmd
          - href: modules/module2/module2-01-reading_in_different_file_types.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module2/module2-02-delimiter.qmd
          - href: modules/module2/module2-06-arguments_for_reading_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module2/module2-07-name_that_argument.qmd
          - href: modules/module2/module2-09-column_renaming_and_dropping.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module2/module2-10-column_editing_questions.qmd
          - href: modules/module2/module2-13-column_arithmetic_and_creation.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module2/module2-14-column_arithmetic_questions.qmd
          - href: modules/module2/module2-16-data_filtering.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module2/module2-17-filtering_question.qmd
          - href: modules/module2/module2-20-conditional_value_replacement.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module2/module2-21-practice_replacing_values.qmd
          - href: modules/module2/module2-22-chaining_notation.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module2/module2-23-chaining_true_false.qmd
          - href: modules/module2/module2-25-grouping_and_aggregating.qmd
          - text: '&nbsp;&nbsp; 8.1. Exercises'
            href: modules/module2/module2-26-fruit_salad_grouping_and_aggregating.qmd
          - href: modules/module2/module2-29-plotting_with_altair.qmd
          - text: '&nbsp;&nbsp; 9.1. Exercises'
            href: modules/module2/module2-30-plotting_a_groupby_object.qmd
          - href: modules/module2/module2-31-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true