project:
  type: website
  title: "Programming in Python for Data Science"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**Module 5: Making Choices and Repeating Iterations**"
        contents:
          - href: modules/module5/module5-00-module_learning_outcomes.qmd
          - href: modules/module5/module5-01-making_choices_with_conditional_statements.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module5/module5-02-quick_questions_with_conditionals.qmd
          - href: modules/module5/module5-06-repeated_iterations_(loops).qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module5/module5-07-repeated_iterations_questions.qmd
          - href: modules/module5/module5-09-range_dictionaries_and_comprehensions.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module5/module5-10-range_questions.qmd
          - href: modules/module5/module5-13-nested_loops.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module5/module5-14-nested_loop_questions.qmd
          - href: modules/module5/module5-16-repeated_iterations_with_conditions.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module5/module5-17-conditional_loop_questions.qmd
          - href: modules/module5/module5-19-functions.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module5/module5-20-function_questions.qmd
          - href: modules/module5/module5-23-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true