project:
  type: website
  title: "Programming in Python for Data Science"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome to Programming in Python for Data Science**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-programming_in_python_for_data_science.qmd
          - text: '&nbsp;&nbsp; 1.1. Prerequisite confirmation'
            href: modules/module0/module0-02-are_you_ready.qmd
      - section: "**M1. Python & Pandas - An Unexpected Friendship**"
        contents:
          - href: modules/module1/module1-00-module_learning_outcomes.qmd
          - href: modules/module1/module1-01-introduction_to_dataframes.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-describing_a_dataframe.qmd
          - href: modules/module1/module1-03-introduction_to_pandas.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module1/module1-04-definitions.qmd
          - href: modules/module1/module1-07-slicing_with_pandas_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module1/module1-08-slicing_and_dicing_practice.qmd
          - href: modules/module1/module1-11-slicing_columns_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module1/module1-12-slicing_columns_only.qmd
          - href: modules/module1/module1-13-selecting_using_.loc[].qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module1/module1-14-rearraging_columns_and_rows.qmd
          - href: modules/module1/module1-16-obtaining_dataframe_values.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module1/module1-17-practicing_selecting_values.qmd
          - href: modules/module1/module1-18-selecting_a_single_column.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module1/module1-19-practicing_selecting.qmd
          - href: modules/module1/module1-20-slicing_and_selecting_using_df.iloc[].qmd
          - text: '&nbsp;&nbsp; 8.1. Exercises'
            href: modules/module1/module1-21-practicing_slicing_and_selecting_using_index_position.qmd
          - href: modules/module1/module1-24-sorting_dataframes.qmd
          - text: '&nbsp;&nbsp; 9.1. Exercises'
            href: modules/module1/module1-25-practice_sorting.qmd
          - href: modules/module1/module1-26-summary_statistics.qmd
          - text: '&nbsp;&nbsp; 10.1. Exercises'
            href: modules/module1/module1-27-fruit_bowl_statistics.qmd
          - href: modules/module1/module1-29-frequency_tables_and_writing_csvs.qmd
          - text: '&nbsp;&nbsp; 11.1. Exercises'
            href: modules/module1/module1-30-practicing_frequency_tables.qmd
          - href: modules/module1/module1-31-quick_viz_with_altair.qmd
          - text: '&nbsp;&nbsp; 12.1. Exercises'
            href: modules/module1/module1-32-practicing_bar_charts.qmd
          - href: modules/module1/module1-34-what_did_we_just_learn.qmd
      - section: "**M3. Tidy Data and Joining Dataframes**"
        contents:
          - href: modules/module3/module3-00-module_learning_outcomes.qmd
          - href: modules/module3/module3-01-what_is_tidy_data.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module3/module3-02-tidy_data_questions.qmd
          - href: modules/module3/module3-05-statistical_questions_and_tidy_data.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module3/module3-06-which_is_tidy.qmd
          - href: modules/module3/module3-08-reshaping_with_pivot.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-09-pivoting_questions.qmd
          - href: modules/module3/module3-11-reshaping_with_pivot_table.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module3/module3-12-pivot_table_questions.qmd
          - href: modules/module3/module3-14-reshaping_with_melt.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module3/module3-15-melting_questions.qmd
          - href: modules/module3/module3-17-concatenation.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module3/module3-18-concat_questions.qmd
          - href: modules/module3/module3-21-joining_dataframes_using_merge.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module3/module3-22-merge_questions.qmd
          - href: modules/module3/module3-25-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#003366'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true