name: 'kcds-prog'
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.11,<3.13
    - altair-all=5.5.*
    - pandas=2.2.*
    - scipy
    - matplotlib
    - jupyter
    - quarto=1.6.43
    - pip


