---
params:
  dynamictitle: "module2_24"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../../../static/module2/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)

df = pd.read_csv('cereal.csv')
```


type: slides

# Plotting Groupby Objects


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's return to the question we asked at the beginning slides of exercise 25: 

_*Which manufacturer has the highest mean sugar content?*_   

A nice way of showing our results would be to graph this. A bar chart like this should do the trick! 


```{python echo=FALSE, fig.width = 6, fig.height = 4}
sugar_plot = (df.groupby(by='mfr')
                .mean()
                .loc[:,'sugars']
                .plot.bar(title='Mean sugar content among manufacturers')
              )
sugar_plot.set_ylabel('Sugar content (in grams)', fontsize=12)
sugar_plot = sugar_plot.set_xlabel('Manufacturer', fontsize=12)
sugar_plot
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's go through the steps that are needed to make this plot. 

- We are going to save our plot as an object named `sugar_plot` and use our chaining technique as well. 
- We create a groupby object and calculate the mean for each column in the dataframe.       
- Next, we take the single column we are interested in using `.loc[]`.              
- Our last action is the plot everything using `.plot.bar()`.  


```python
sugar_plot = (df.groupby(by='mfr')
                .mean()
                .loc[:,'sugars']
                .plot.bar()
             )
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

```{python fig.width = 6, fig.height = 4, fig.asp = .62}
sugar_plot = (df.groupby(by='mfr')
                .mean()
                .loc[:,'sugars']
                .plot.bar()
             )
sugar_plot
```
  
This plot, however, looks a little unfinished. We need to add a title and label our y-axis. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We've added a title before, so there is nothing new there but adding x and y-axis labels is a little different. We can increase the label font sizes using the argument `fontsize`. In this case, we reference our initial plot and use the verb `.set_ylabel()` and `.set_xlabel()` with the desired axis label as an argument and `fontsize` to assign a desired label size. 
To avoid unnecessary information that will be returned otherwise, whatever our last verb being used with our plot (named `sugar_plot) has to be reassigned back to the object. If we did this any other way, we would not have the ability to do more transformations on our plot, or we would get additional information with the plot output. 

```{python  out.width = '45%', fig.asp = .40}
sugar_plot = (df.groupby(by='mfr')
                .mean()
                .loc[:,'sugars']
                .plot.bar(title='Mean sugar content among manufacturers')
              )
sugar_plot.set_ylabel('Sugar content (in grams)', fontsize=9)
sugar_plot = sugar_plot.set_xlabel('Manufacturer', fontsize=9)
sugar_plot
```



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

In the last plot, we used `.loc[:,'sugars']` to select a single column to the plot, however, we can show multiple mean column values in a single plot by selecting more columns. The columns `fat`, `fiber` and `protein` seem like good choices. 

```{python out.width = '60%', fig.asp = .58}
nutrition_plot = (df.groupby(by='mfr')
                    .mean()
                    .loc[:, ['fat', 'fiber', 'protein']]
                    .plot.bar(title='Mean nutritrion value over different manufacturers')
                 )
nutrition_plot.set_ylabel('Content (in grams)', fontsize=9)
nutrition_plot = nutrition_plot.set_xlabel('Manufacturer', fontsize=9)
nutrition_plot
```


If you want high fibre and low fat, consider having N's cereals for breakfast (or lunch or dinner)!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Multiple Grouping 

We can group by multiple columns as well. 
For example we can grouping by not only manufacturer but also by cereal type! All we do is put both both column labels in square brackets within `.groupby()`.

```{python}
mfr_type_group = df.groupby(by=['mfr', 'type'])
mfr_type_group.groups
```

The attribute `ngroups` indicates how many groups there are.  

```{python}
mfr_type_group.ngroups
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

If we want to get the dataframe of a specific group now, we put the value of each column in parentheses. 

```{python}
mfr_type_group.get_group(('K', 'Cold'))
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We can plot in the same way as before 

```{python fig.width = 13, fig.height = 9,  out.width = '50%'}
type_plot = (df.groupby(by=['mfr', 'type'])
                    .mean()
                    .loc[:, ['sugars']]
                    .plot.bar(title='Mean sugar value over different manufacturers and types'))
type_plot.set_ylabel('Sugar (in grams)', fontsize=16)
type_plot.set_xlabel('Manufacturer and cereal type', fontsize=16)
type_plot
```




Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Using `pandas` to plot groupby objects is very limited and is not possible for many other plot types such as scatter plots.      
If you wish to learn more advanced visualization and Python plotting package **Altair**, come back soon and visit our in development course **DSCI-031 Exploratory Data Visualization**. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---



# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>
