---
params:
  dynamictitle: "module2_19"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../static/module2/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)

df = pd.read_csv('cereal.csv', index_col=0)
```


type: slides

# Conditional Value Replacement and Assignment 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Building on things we know

In the last module, we explored `.loc[]` and how it can help slice and select specific columns and rows in a dataframe, however, the power of `.loc[]` does not stop there.       
This section marks the return of `.loc[]` and how it can replace certain values within a dataframe that meet specified conditions. 

Keeping with our routine, we are bringing in our cereal dataset in once again.  Are you starting to get familiar with this dataset yet? 

```{python}
df = pd.read_csv('cereal.csv', index_col=0)
df.head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# The return of loc

We have discussed how `.loc[]` can select and return specified columns and rows of the dataframe. 
In this module, `.loc[]` will be used to locate specific rows conditionally on their column values. This is done similarly to how we filtered our dataframe but with 2 distinct differences:    
  
1. We use `.loc[]` to find the rows specifying certain conditions.      
2. Once we have obtained our desired rows we replace their values in either a specified column or create a new column altogether.       

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---


In our cereal dataframe, the manufacturer value "Q" isn't that informative and it might be easier to understand our data if we change all these values to something more complete like "Quaker".

Let's start by simply finding all the cereals made by the "Quaker Oats" manufacturer: 

```{python}
df.loc[df['mfr'] == 'Q']
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

You may look at the above syntax and think "Wait, didn't we do something similar when we were filtering in the last section?".  You're right! 

We used similar syntax when we filter, however, now we've added the verb `.loc[]`. 

To replace "Q" with "Quaker",  we indicate which column we are editing as the second argument (which we can't do, if we do not use `.loc[]`).       
In our scenario, we are editing the `mfr` column.      
This code results in a single column dataframe with only "Q" values.

```{python}
df.loc[df['mfr'] == 'Q', 'mfr']  
```


Notes: Script here
<html>
<audio controls >
  <source src=/"placeholder_audio.mp3" />
</audio></html>

---

Lastly, we need to specify yo what we want to change the values.  In our case, we are replacing "Q" with "Quaker".

```{python}
df.loc[df['mfr'] == 'Q', 'mfr'] = 'Quaker'
```

Wait!  Nothing was outputted with this code!  What happened?  Let's take a look at our dataframe.

```{python}
df.head()
```

We can now see that `100% Natural Bran's` manufacturer value has changed to `Quaker` but what about the rest of them? 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's filter and see!

```{python}
df[df['mfr'] == 'Quaker']  
```

Great, all the "Q" values have been replaced with "Quaker".     
When we use this syntax, we do not need to save the results in a new object name like we had to with `.assign()` and `.drop()`. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Replacing with Inequalities. 

This also works for inequality conditions.

If we are replacing numerical values with characters or words (or vice versa) we need to assign our desired values to a **new column** and not the existing one.    
Perhaps we want just 2 categories for protein levels -"high" and "low".  Any cereal above 3 grams of protein will be considered a "high" protein level and anything less, as a "low" protein level. 

Let's assign the "high" protein values first.  The only difference here from earlier is we now use an inequality for our condition and we designate a new column name instead of an existing one.  Let's save the values in a column named `protein_level`.

```{python}
df.loc[df['protein'] >= 3, 'protein_level']  = 'high' 
```

Next by the "low" values.

```{python}
df.loc[df['protein'] < 3, 'protein_level']  = 'low' 
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's see the results by scrolling to the right of the dataframe.
```{python}
df.head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>
