---
title: "module1_19"
output:
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                            
opts_chunk = NULL,
                            
knit_hooks = NULL,
                            
opts_hooks = NULL,
                            
opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
             
base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
```


type: slides

# Slicing and Selecting using df.iloc[]


Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

## Slicing Dataframe

Up to this point, we have been manipulating our dataframe with column and row _**label**_ name using `df. loc`.     
`df.iloc` is very similar, however, the "i" in `iloc` refers to the index _**integer**_ position.    

Let's return to our cereal dataset and take a look at the first 15 rows.


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

```{python}
df = pd.read_csv('cereal.csv', index_col = 0)
df.head(15)
```



Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Let's say we want the rows `All-Bran` to `Apple Cinnamon Cheerios` but we want to slice based on their position.  
Using Python's counting method of starting at zero, we conclude `All-Bran` to be at position to 2.

```{python echo= FALSE}
df.head(7)
```


We get `Apple Cinnamon Cheerios` position to be 5 in the same way.


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

 We can use the same coding structure we learned with `df.loc`, but this time using the position instead of labels with `df.iloc[]`

```{python}
df.iloc[2:5]
```


But wait! Something is missing here!

Why doesn't "Apple Cinnamon Cheerios" appear in the dataframe? 


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

That's because when we use slicing by index position, it will take all the indices including the lower bound but _EXCLUDING_ the upper bound. If we wanted to include "Apple Cinnamon Cheerios" we would have to go 1 index position further.

```{python}
df.iloc[2:6]
```


Ah, that's better.  

Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

The same concepts can apply to the columns of the dataframe.   
Let's say we want all the rows but we only want the columns starting at `protein` and ending (including) at column `sugars`.     
Using the logic we learned in the last set of slides, we would use the following code:

```{python}
df.iloc[ : ,  3:9 ]
```

We would need to specify all rows using ` : ` as we did when we used `df.loc[]`. The column `protein` is at index position 3 and `sugars` is at index position 8, but since we want to include the 8th column we need to use the 9th position to make sure we get all the columns _BEFORE_ the upper bound.


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>


---

The same would apply if we only wanted certain rows with certain columns. Let’s say we want the rows 
`All-Bran` to `Apple Cinnamon Cheerios` and `protein` to `sugars`.     
**Rows**    
`All-Bran` located at position 2.     
`Apple Cinnamon Cheerios` is located at position 5.     
**Columns**   
`protein` is located at position 3.     
`sugar` is located at position 8.

```{python}
df.iloc[2:6, 3:9]
```


Both of our upper bound have been compensated with + 1 to make sure they are included in the new dataframe.


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

## Selecting with df.iloc[]

Selecting using `iloc` is done identically to `loc`, however, the items within each set of square brackets **MUST** be numeric.

Let’s say we want the rows `Cheerios`, `Basic 4` and `Apple Jacks`  with the columns `rating`, `fat` and `type` _in that order_.

**Rows**    
`Cheerios` is located at position 11.     
`Basic 4` is located at position 7.    
`Apple Jacks` is located at position 6.

**Columns**   
`rating` is located at position 14.  
`fat` is located at position 4. 
`type` is located at position 1.  

Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Now let's put those position into square backing within `df.iloc[]`

Recap the locations: `Cheerios` = 2, `Basic 4` = 5 and `Apple Jacks` = 3, `rating` = 14, `fat` = 4, `type` = 1.   

```{python}
df.iloc[[11, 7, 6], [14, 4, 1]]
```


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>


---

# Nice work! Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>
