---
params:
  dynamictitle: "module2_16"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../static/module2/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)

df = pd.read_csv('cereal.csv', index_col=0)
```


type: slides

# Conditional Value Replacement


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

# Building on things we know

Last module we explored `.loc[]` and how it can help slice and select specific columns and rows in a dataframe. The power of it however is not limited to just that. This section marks the return of `.loc[]` and how it canreplace certain values within a dataframe that meet specified conditions. 

As routine practice, we are bringing in our cereal dataset in once again. Are you starting to get familiar with it yet? 

```{python}
df = pd.read_csv('cereal.csv', index_col=0)
df.head()
```


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

# The return of loc

In the previous module we discussed how `.loc[]` take the _*location*_ of specified columns and rows labels of the dataframe and returns them. 
In this module, loc will continue to locate specific rows conditionally on certain column values similarly to how filter is used, however. now we are replacing the column value. 

In our cereal dataframe, the manufacturer value "Q" isn't that informative and it might be easier to understand if we change all these values to something more understandable like "Quaker".

Let's start by simply finding all the cereals made by the "Quaker Oats" manufacturer: 

```{python}
df.loc[df['mfr'] == 'Q']
```


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

You may look at the above syntax and think "Wait, we did something similar when we were filtering in the last section?". You're right! 

We used simiar syntax when we filter, however, now we've added the verb `.loc[]`. In order to replace "Q" with "Quaker", however,  we need to indicate which column we are editing as the second argument (which we can't do, if we leave out `.loc[]`) . In this example we are editing the `mfr` column. 
This code results in a single column dataframe with only "Q" values.

```{python}
df.loc[df['mfr'] == 'Q', 'mfr']  
```


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Lastly, to complete our code we need to specify what we want to change the values to! What we want these values to _equal_ to now. 

```{python}
df.loc[df['mfr'] == 'Q', 'mfr'] = 'Quaker'
```

Wait! Nothing was outputted with this code! What happened? Let's take a look at our dataframe 

```{python}
df.head()
```

I can now see that `100% Natural Bran`'s manufacturer value has changed to `Quaker` but what about the rest of them? 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Let's filter and see!

```{python}
df[df['mfr'] == 'Quaker']  
```

Great, all the "Q" values have been replaced with "Quaker". 
We see that when we use this syntax, we do not need to save the results in a new dataframe, like we had to with `.assign()` and `.drop()`. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

This also works for inequality conditions. Let's say instead of displaying the protein protein content numerically, we instead either have high or low protein levels. Let's classify 3 grams or larger as "high" protein and anything less, as low. 

Let's change the "high" protein values first:

```{python}
df.loc[df['protein'] >= 3, 'protein']  = 'High' 
```

Followed by the "low" values.

```{python}
#df.loc[df['protein'] < 2, 'protein']  = 'low' 
```

```{python}
df
```


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>