---
params:
  dynamictitle: "module2_10"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../static/module2/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 8)

df = pd.read_csv('cereal.csv', index_col=0)
```


type: slides

# Filtering 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Filtering is probably one of the most frequent data maniputation you will do in data analysis. Filtering is often used when we are either trying to rid the dataframe of unwanted rows, or analyze rows with a particular column value. 

Think of it as a sieve keeping only the rows matching conditions you have set. 

Let's welcome back the `cereal.csv` data we have worked with in Module 1. 

```{python}
df = pd.read_csv('cereal.csv', index_col=0)
df.head()
```



Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

## Standard filtering 

Suppose you are trying to find a cereal with a protein content greater than 4g per serving. We can find those rows with the following code.  
```{python}
df[ df['protein'] > 4]
```

This is a little tricky because we first specify the dataframe `df` and within it's square brackets, we specify the  column attempting to be filtered  with `df['protein']` followed by the condition. 


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

We can do with not only with inequalities but with equal to as well. 

```{python}
df[ df['protein'] == 4]
```

Now we get all the cereals with a protein content of 4g per serving. The key point to remember here is that we use **2** equal signs, else our code will return an error. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

We can filter on categorical columns too. In this example maybe I want only cereals from the manufacturer "Q" (For Quackers)

```{python}
df[ df['mfr'] == 'Q']
```

Here we are using the double equal signs we saw above. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

##  Multiple Condition Filtering - "and"

We now know how to filter on one condition but how do we filter if we have many? 
Let's say we only wanted cereals with a protein content between 4 to 5 groms?
```{python}
df[ (df['protein'] >= 4) & (df['protein'] <= 5) ]
```

Code Explained:     
We need to use the special symbol `&` meaning "and". This means that both conditions must hold true to be returned in the new dataframe. 
Each condition is wrapped with parentheses to distinguish each condition from one another. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Let's try a case where we filter on 2 different columns. Let's say we only want hot cereals with a fiber content greater than 2. 

```{python}
df[ (df['type'] == 'Hot') & (df['fiber'] > 2)]
```

The same rules apply to 2 different column conditions. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

##  Multiple Condition Filtering - or

Now suppose that we are interested in cereals that either have a fiber content greater that 6 **OR** a protein content above 5. We only need one of these conditions to hold to return a row. 

```{python}
df[ (df['fiber'] > 6) | (df['protein'] > 5)]
```

Instead of using the ` & ` symbol we use ` | ` which is called the "pipe operator". This means "or" in the Python programming language. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

If we wanted a dataframe that met both conditions using "and" (`&`). This is what would happen

```{python}
df[ (df['fiber'] > 6) & (df['protein'] > 5)]
```

Since no rows meet both conditions, a dataframe with zero rows is returned. 

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

## Multiple Condition Filtering 

Let's do one more examples where we use both "and" as well as "or"

Let's build on condition of wanted cereals that either have a fiber content greater that 6 **OR** a protein content above 5 but this time we only want those cereals from the manufacturer "K". 

```{python}

df[ ((df['fiber'] > 6) | (df['protein'] > 5)) & (df['mfr'] == 'K') ]
```


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

We need to take great care on including parentheses when needed. If we did not include parentheses around our "or" conditions, this is what would have been returned:

```{python}
df[ (df['fiber'] > 6) | (df['protein'] > 5) & (df['mfr'] == 'K') ]
```

Python will now move from left to right and in this case it will select all the cereals with a fiber content greater than 6 *or* all the cereal satisfying a protein content above 5 made by manufacturer  "K". 


Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>