---
title: "Module1_07"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
```

type: slides

# Slicing with Pandas Using df.loc

Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

Congratulations on writing your first code! This is great! We have read in our data and know the dimensions. What now? Let's go over how we would **index**, **slice** and  **select** certain columns or rows of our data.


Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

## Cereal Data

Let's import pandas and bring in a dataset named `cereal.csv` using the name of the cereals as the index like we did last time with `index_col=0`.

Attribution:     
_“[80 Cereals](https://www.kaggle.com/crawford/80-cereals/)” (c) by [Chris Crawford](https://www.linkedin.com/in/crawforc3/) is licensed under [Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/)_

```{python }
import pandas as pd
  
df = pd.read_csv('cereal.csv', index_col=0)
df.head()
```

  
Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>
    
---

## The Index
    
We can see all the columns and the first 5 rows of the dataframe.
Let's say we only want certain rows of the whole dataframe or certain columns.

We talked about how `df.head()` will generate the first few rows (5 as default) of a dataframe but what if we wanted rows 5-10?

The first column of this dataframe is called the `index`. This is what we specified with `index_col=0` when we read in our data with `pd.read_csv()`. Each row has a label (the index) as well as a position. In this case, the index label of an observation is the cereal name and the index position is where it lies in the dataframe.The index label doesn't alway have to be named with words, they could be also named with a number which can get confusing. 

Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

Here are the first 10 rows of the dataframe: 

```{python}
df.head(10)
```

Let's talk about the observation named `Almond Delight`.  Its index label is `Almond Delight` but its index position is 4.    
If you just went and counted those again and started screaming "5! It's the fifth position", that's ok. In the Python language, we start counting at position 0 (then 1, 2, 3, and 4 for Almond Delight).
  
Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

So now let's say we want the 5 rows past `Almond Delight`. That means we want rows with the index labels `Apple Cinnamon Cheerios` to `Cap'n'Crunch`.    
The following code cuts the dataframe from  "Apple Cinnamon Cheerios" to "Cap'n'Crunch" keeping all the columns.

```{python}
df.loc[ 'Apple Cinnamon Cheerios' : "Cap'n'Crunch"]
```

```df.loc[ 'Apple Cinnamon Cheerios' : "Cap'n'Crunch"]```

This essentially means to  _Obtain the values in the dataframe location from `Apple Cinnamon Cheerios` to `Cap'n'Crunch`._       
      
_Quotation remark: You may notice that we use single quotes for `Apple Cinnamon Cheerios` and double quotes for `Cap'n'Crunch`. This is because there are apostrophes in the name `Cap'n'Crunch which prevents the outer ones from working properly. Using double quotations in this case will fix this problem._  

Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3"/>
</audio></html>

---

What if we only wanted certain columns now?

Perhaps we were only interested in the `calories` to `fiber` columns of the "Apple Cinnamon Cheerios" to "Cap'n'Crunch" rows?
We put our desired rows first, then columns and separate them with a comma.  


```{python}
df.loc[ 'Apple Cinnamon Cheerios' : "Cap'n'Crunch", 'calories' : 'fiber']
```

`loc` is used to slice columns and rows by **label** and within an interval.

The general format to slice both rows and columns together looks like this:

```python
`df.loc[ 'row name start' : 'row name end' , 'column name start' : 'column name end']`
```


Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

# Let’s try it out!
    
Notes: Script here
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>
    