---
title: "module1_13"
author: "Hayley Boyce"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
df = pd.read_csv('cereal.csv', index_col=0)
```


type: slides

# Selecting using df.loc[]

Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

So to answer the question where we left off, after giving it a try, you know that rearranging column or row order is as easy as changing the column name order!

So if we wanted the rows to be in the order  `Wheaties`, `Trix` and `Clusters` and columns in the order `type`, `rating` and `sugars` from our cereal dataframe,
we would obtain it like so:

```{python}
df.loc[ ["Wheaties", "Trix", "Clusters"] , ["type", "rating", "sugars"] ]
```


Notes: Script here.
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>

---

# Selecting a Single Column

Something extremely useful is getting a single column from a dataframe.
We can use `df.loc[]` which would look something like this:

```
df.loc[ : , [ "column-name"] ]
```

For example, if we wanted the column `type` from our cereal dataframe.
```{python}
df.loc[ : , [ "type"] ]
```

But there is a better way of doing this.

Notes: Script here.
<html>
<audio controls >
<source src="placeholder_audio.mp3" />
</audio></html>

---

You can omit `loc` altogether and use double square brackets:

``` Python
df[['column-name']]
```

Selecting the column `type` would be as simple as so:

```{python}
df[['type']]
```

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="placeholder_audio.mp3" />
</audio></html>