---
format: revealjs
title: What Did we Learn and What to Expect in Assignment 8
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```

## Summary  

Students are now expected to be able to:

- Use NumPy to create ndarrays with `np.array()` and from functions such as `np.arange()`, `np.linspace()` and `np.ones()`.
- Describe the shape, dimension and size of an array.
- Identify null values in a dataframe and manage them by removing them using `.dropna()` or replacing them using `.fillna()`.
- Manipulate non-standard date/time formats into standard Pandas datetime using `pd.to_datetime()`.
- Find, and replace text from a dataframe using verbs such as `.replace()`. 


:::{.notes}
The assignment will concentrate on the learning objectives as well as building knowledge on existing concepts. 
:::

---

## Attribution

The cereal dataset:

 “[80 Cereals](https://www.kaggle.com/crawford/80-cereals/)” (c) by [Chris Crawford](https://www.linkedin.com/in/crawforc3/) is licensed
under [Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/)



# On to Assignment 8!
