---
format: revealjs
title: Introduction to Working with Strings
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```

## Recap 

Let's first remind ourselves of some of the methods we've already learned such as:

- `.upper()`
- `.lower()` 
- `.count()`
- `.split()` 


```{python}
instrument = 'Violin'
instrument
```

<br>

```{python}
instrument.upper()
```


:::{.notes} 
Although we have already introduced you to strings to a certain degree, processing and working with this data type is an area that will require a substantial amount of learning. 

In this course, we will only scratch the surface when it comes to strings. 

That being said, we do hope to provide you with an adequate foundation in string processing. 

Let's first remind ourselves of some of the methods we've already learned such as:

- `.upper()`
- `.lower()` 
- `.uppercase()`
- `.count()`
- `.split()` 

When we work with just a general string, we can just use the function at the end of the object name. 

For example, if our string object name was `instrument`.

We could convert to all uppercase characters with `instrument.upper()`.
:::

---

```{python}
instrument.lower()
```

<br>

```{python}
instrument.count('i')
```

<br>

```{python}
instrument.split('i')
```


:::{.notes} 
Or convert the string to lowercase with `instrument.lower()`.

We could count the number of occurrences of the letter "i" using `instrument.count('i')`

And split a string on a specified character (for example, in this case, "i") using the code `instrument.split('i')`.
:::

---

## Processing String Columns

```{python}
# | include: false
cycling = pd.read_csv('data/cycling_data.csv')
```

```{python}
cycling
```

:::{.notes} 
The only problem is that when we work with data, we will be applying these transformations, not to a single string, but to a whole column of them. 

We saw back in Module 4 that string data is represented in a pandas dataframe using the dtype `object`. 

This is the default dtype given to columns that have a mix of different data types or if pandas cannot identify the column as any other dtype. 

Let's bring back our `cycling` dataframe to demonstrate how to work with columns of this dtype. 

:::

---

```{python}
# | include: false
cycling = pd.read_csv('data/cycling_data.csv')
```

```{python}
upper_cycle = cycling.assign(Comments = cycling['Comments'].str.upper())
upper_cycle.head()
```

<br>

```{python}
rain_cycle = upper_cycle.assign(Rain = upper_cycle['Comments'].str.count('RAIN'))
rain_cycle.head()
```


:::{.notes} 
Remember when we discussed datetimes columns, and we applied time functions to a whole column by adding `.dt` before the function? 

We can use that same syntax style when applying string transformations to entire columns but this time using `.str`.

Perhaps we wanted the entire `Comments` column from our `cycling` dataframe in uppercase. 

We can use `.assign()` and `.upper` paired with `.str` to transform the column.

Not too, shabby! 

How about we add a new column that contains the number of times "RAIN" is counted in `upper_cycle`.

Again we use `.str.count('RAIN')`
:::

---

```{python}
upper_cycle['Comments'].str.split(expand=True)
```


:::{.notes} 
We've also seen this syntax when we used `str.split()` in Module 4 when we learned about splitting our columns.

Here we split up every word in the `Comments` column and created a new column for each.
:::

---

```{python}
"My favorite colour" + "is Blue"
```

<br>

```{python}
combined_cycle = cycling.assign(Distance_str = cycling['Distance'].astype('str') + ' km')
combined_cycle.head()
```


:::{.notes}
Another operation that we've lightly touched on is the concatenation of strings. For instance, when we add 2 strings together: 

This can be implemented in dataframes too by concatenating a column with `str` values with another `str` and create a column:
:::

---

```{python}
upper_cycle.head(3)
```

<br>

```{python}
cap_cycle = upper_cycle.assign(Comments = upper_cycle['Comments'].str.capitalize())
cap_cycle.head(3)
```

<br>

```{python}
cap_cycle = upper_cycle.assign(Comments = upper_cycle['Comments'].str.title())
cap_cycle.head(3)
```


:::{.notes} 
A new function we haven't discussed but is quite similar to `.upper()` and `.lower()` is`.capitalize()` which capitalizes the first word of the string.

Another is `.title()`, which capitalizes the first letter of every word in a string.
:::

---

## Strip

<a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.strip.html" target="_blank">`.strip()` </a>.


```{python}
"Sunshine" == " Sunshine "
```

<br>

```{python}
string1 = " Sunshine " 
new_string1 = string1.strip()
new_string1
```

<br>

```{python}
"Sunshine" == new_string1
```


:::{.notes} 
One function that might not seem that pertinent but is extremely useful is <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.strip.html" target="_blank">`.strip()` </a>.

`strip()` removes characters starting or ending a string, with the default being spaces. 

For Example:

To us, reading "Sunshine" and " Sunshine " are the same thing, but to Python, they are quite different because of the blank space surrounding it. 

The blank space on either side of a string often needs to be removed depending on the analysis. 

We can remove them in the example above using `strip()`.
:::

---

```{python}
cycling.head()
```

<br>

```{python}
cycling[cycling['Comments'] == 'Rain']
```


:::{.notes} 
This can be especially frustrating when we are trying to filter dataframes.

Let's try to filter our data to find rows where the value for the `Comments` column is "Rain". 

We can see that index 0 should be filtered out, but pandas does not recognize it with the trailing blank space.

No rows are outputted. That's because there is a blank space following "Rain".
:::

---

```{python}
stripped_cycling = cycling.assign(Comments = cycling['Comments'].str.strip())
stripped_cycling.head()
```

<br>

```{python}
stripped_cycling[stripped_cycling['Comments'] == 'Rain']
```


:::{.notes} 
Let's now strip our column using `.strip()` and assigning the changes to the `Comments` column of a dataframe named `stripped_cycling`. 

Since we are using `.strip()` with a dataframe column, we have to add `.str`.

This time, when we filter on `Rain` on our new `stripped_cycling` dataframe, pandas filters out the row!

Ahh, that's much better!
:::

---

```{python}
stripped_cycling.tail(5)
```

<br>

```{python}
stripped_cycling['Comments'].str.strip("!").tail()
```


:::{.notes} 
We are not limited to stripping the values of white space. We can also strip any other character. Let's try punctuation!

We can see that index 30 has a value of `Feeling good after a holiday break!` in the `Comments` column. 

After using `str.strip('!')` we can see that it's no longer has the exclamation mark! 
:::


# Let’s apply what we learned!