---
params:
  dynamictitle: "module2_09"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../static/module2/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 8)

df = pd.read_csv('cereal.csv', index_col=0)
```

type: slides

# Column Renaming and Column Dropping


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Remember our `candybars.csv` dataframe?  Let's bring it back. 


```{python}
df = pd.read_csv('candybars.csv', index_col=0)
df
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Column Renaming

There will be times where you are unsatisfied with the column names and you may want to change them.  The proper syntax to do that is with `df.rename()` and saving the dataframe as an object.    
The column named `available_canada_america` is a bit long. Perhaps it would be a good idea to change it something shorter like `availability`. 
Here is how we can accomplish that. 


```{python}
df = df.rename(columns={'available_canada_america':'availability'})
df.head()
```


This code uses something we've never seen before - {} curly brackets.
These have a special meaning but for now, you only need to concentrate your attention on the fact that the argument `columns` needs to have the format:

```
 columns={'old-column-name':'new-column-name'}
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

You can also rename multiple columns at once by simple adding a comma between the new and old column pairs within the curly brackets. 

```{python}
df = df.rename(columns={'available_canada_america' : 'availability',
                        'weight' : 'weight_g'})
df.head()
```


It's important that we always save the dataframe to an object when making column changes or the changes will not be saved in our dataframe.

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---


## Column Dropping 

`df.drop()` is used when renaming the column labels is not enough and we just don't want certain columns in the dataframe at all. 
Let's delete the column `coconut`. 


```{python}
df.drop(columns='coconut')
```



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

If you scroll back to the last slide you'll notice we didn't save over the dataframe object, so the dataframe `df` still will contain `coconut`.

```{python}
df.head()
```

Let's overwrite this and remove multiple columns at the same time. Let's drop `nougat` and `coconut` together. We put the columns we want to drop in square brackets and this time we will remember to overwrite over the `df` object.

```{python}
df = df.drop(columns=['nougat', 'coconut'])
df.head()
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>
