---
format: html
---

<script src='../../src/quiz.js'></script>

# 4.1. Exercises

## Slicing Columns Only


Using my dataframe object named `fruit_salad`, let's answer some slicing questions.

```out
           name    colour    location    seed   shape  sweetness   water-content  weight
0         apple       red     canada    True   round     True          84         100
1        banana    yellow     mexico   False    long     True          75         120
2    cantaloupe    orange      spain    True   round     True          90        1360
3  dragon-fruit   magenta      china    True   round    False          96         600
4    elderberry    purple    austria   False   round     True          80           5
5           fig    purple     turkey   False    oval    False          78          40
6         guava     green     mexico    True    oval     True          83         450
7   huckleberry      blue     canada    True   round     True          73           5
8          kiwi     brown      china    True   round     True          80          76
9         lemon    yellow     mexico   False    oval    False          83          65
```

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'If you wanted all the rows and only columns <code>seed</code>, <code>shape</code>, <code>sweetness</code> and  <code>water-content</code>, what would your code look like using index labels?',
        {
        '<code>fruit_salad.loc[:, "seed":"weight"]</code>': 'This is almost right but it may be good to check your columns.',
        '<code>fruit_salad[:, "seed":"water-content"]</code>': 'This is almost right but it’s missing something important! Try looking at the title of the slides we just finished.',
        '<code>fruit_salad[0:9, "seed":"water-content"]</code>': 'This is almost right but it’s missing something important and it could be condensed! Try looking at the title of the slides we just finished.',
        '<code>fruit_salad.loc[:, "seed":"water-content"]</code>': 'Good job! This has both <code>.loc[]</code> and includes the columns we wish to slice here.',
        },
        '<code>fruit_salad.loc[:, "seed":"water-content"]</code>',
    );
</script>
