---
format: live-html
---

<script src='../../src/quiz.js'></script>

# 6.1. Exercises

## Practicing Selecting Values

**Instructions:**    
Running a coding exercise for the first time, could take a bit of time for everything to load. Be patient, it could take a few minutes.   

**When you see `____` in a coding exercise, replace it with what you assume to be the correct code. Run it and see if you obtain the desired output. Submit your code to validate if you were correct.**

Use the output of the following code chunk to help complete the next tasks.

```{pyodide}
import pandas as pd
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 25)

# The data
hockey_players = pd.read_csv('data/canucks.csv')
hockey_players
```

Using our `hockey_players` data, try finding the following values and save them in their repective object names.

**Tasks:**

- Save`Thatcher Demko`'s salary in an object named`demko_paid`. 
- How old is `Zack MacEwen`? Save it as object `macewen_age`.
- What position does `Jacob Markstrom` play? Save this as object `markstrom_position`.
- When was `Justin Bailey` born? Save it as an object named `bailey_birth`. 

```{pyodide}
#| setup: true
#| exercise: [practicing_selecting_values_a, practicing_selecting_values_b, practicing_selecting_values_c, practicing_selecting_values_d]
import pandas as pd
from src.utils import print_correct_msg

hockey_players = pd.read_csv('data/canucks.csv')
```

```{pyodide}
#| exercise: practicing_selecting_values_a
# Save Thatcher Demko's salary in an object named demko_paid
____ = ____.____[____, ____]
____
```

```{pyodide}
#| exercise: practicing_selecting_values_a
#| check: true
solution = hockey_players.loc[4, 'Salary']
# displayed as float, but result type is int
assert isinstance(result, int), "The result type is incorrect."
assert solution == result, "Are you selecting the correct value?"
print_correct_msg()
```

:::: { .hint exercise="practicing_selecting_values_a" }
::: { .callout-note collapse="false" }

## Hint 1

- Are you using `.loc[]` to select the specific values?
- Are you using single `[]` brackets?
- Are you using "quotations"?

:::
::::

:::: { .solution exercise="practicing_selecting_values_a" }
::: { .callout-tip collapse="false" }

## Fully worked solution:

```{pyodide}
# Save Thatcher Demko's salary in an object named demko_paid
demko_paid = hockey_players.loc[4, 'Salary']
demko_paid
```

:::
::::

<br>

```{pyodide}
#| exercise: practicing_selecting_values_b
# How old is Zack MacEwen? Save it as object macewen_age
____ = ____.____[____, ____]
____
```

```{pyodide}
#| exercise: practicing_selecting_values_b
#| check: true
solution = hockey_players.loc[10, 'Age']
assert isinstance(result, type(solution)), "The result type is incorrect."
assert solution == result, "Are you selecting the correct value?"
print_correct_msg()
```

:::: { .hint exercise="practicing_selecting_values_b" }
::: { .callout-note collapse="false" }

## Hint 1

- Are you using `.loc[]` to select the specific values?
- Are you using single `[]` brackets?
- Are you using "quotations"?

:::
::::

:::: { .solution exercise="practicing_selecting_values_b" }
::: { .callout-tip collapse="false" }

## Fully worked solution:

```{pyodide}
# How old is Zack MacEwen? Save it as object macewen_age
macewen_age = hockey_players.loc[10, 'Age']
macewen_age
```

:::
::::

<br>

```{pyodide}
#| exercise: practicing_selecting_values_c
# What position does Jacob Markstrom play? Save this as object markstrom_position
____ = ____.____[____, ____]
____
```

```{pyodide}
#| exercise: practicing_selecting_values_c
#| check: true
solution = hockey_players.loc[11, 'Position']
assert isinstance(result, type(solution)), "The result type is incorrect."
assert solution == result, "Are you selecting the correct value?"
print_correct_msg()
```

:::: { .hint exercise="practicing_selecting_values_c" }
::: { .callout-note collapse="false" }

## Hint 1

- Are you using `.loc[]` to select the specific values?
- Are you using single `[]` brackets?
- Are you using "quotations"?

:::
::::

:::: { .solution exercise="practicing_selecting_values_c" }
::: { .callout-tip collapse="false" }

## Fully worked solution:

```{pyodide}
# What position does Jacob Markstrom play? Save this as object markstrom_position
markstrom_position = hockey_players.loc[11, 'Position']
markstrom_position
```

:::
::::

<br>

```{pyodide}
#| exercise: practicing_selecting_values_d
# When was Justin Bailey born? Save it as an object named bailey_birth
____ = ____.____[____, ____]
____
```

```{pyodide}
#| exercise: practicing_selecting_values_d
#| check: true
solution = hockey_players.loc[0, 'Birth Date']
assert isinstance(result, type(solution)), "The result type is incorrect."
assert solution == result, "Are you selecting the correct value?"
print_correct_msg()
```

:::: { .hint exercise="practicing_selecting_values_d" }
::: { .callout-note collapse="false" }

## Hint 1

- Are you using `.loc[]` to select the specific values?
- Are you using single `[]` brackets?
- Are you using "quotations"?

:::
::::

:::: { .solution exercise="practicing_selecting_values_d" }
::: { .callout-tip collapse="false" }

## Fully worked solution:

```{pyodide}
# When was Justin Bailey born? Save it as an object named bailey_birth
bailey_birth = hockey_players.loc[0, 'Birth Date']
bailey_birth
```

:::
::::