---
format: live-html
---

<script src='../../src/quiz.js'></script>

# 5.1. Exercises

## Rearranging Columns and Rows

Using my `fruit_salad` dataframe from earlier...

```out
           name    colour    location    seed   shape  sweetness   water-content  weight
0         apple       red     canada    True   round     True          84         100
1        banana    yellow     mexico   False    long     True          75         120
2    cantaloupe    orange      spain    True   round     True          90        1360
3  dragon-fruit   magenta      china    True   round    False          96         600
4    elderberry    purple    austria   False   round     True          80           5
5           fig    purple     turkey   False    oval    False          78          40
6         guava     green     mexico    True    oval     True          83         450
7   huckleberry      blue     canada    True   round     True          73           5
8          kiwi     brown      china    True   round     True          80          76
9         lemon    yellow     mexico   False    oval    False          83          65
```

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'If I wanted to make a tropical salad and the recipe calls for <code>kiwi</code>, <code>cantaloupe</code> and <code>guava</code> in this order and I am only interested in columns ordered as <code>sweetness</code>, <code>weight</code>, <code>seed</code> and  <code>location</code>, what would my code look like?',
        {
        '<code>fruit_salad.loc[8, 2, 6:"sweetness", "weight", "seed", "location"]</code>': 'Unfortunately, this code has many errors in it.',
        '<code>fruit_salad.loc[[8, 2, 6]:["sweetness", "weight", "seed", "location"]]</code>': 'The way that the rows and columns are separated may need to be looked over.',
        '<code>fruit_salad.loc[[8, 2, 6], ["sweetness", "weight", "seed", "location"]]</code>': 'Yes, this looks right!',
        '<code>fruit_salad.loc[[2, 6, 8], ["location", "seed”, “sweetness", "weight"]]</code>': 'Remember we are rearranging here.',
        },
        '<code>fruit_salad.loc[[8, 2, 6], ["sweetness", "weight", "seed", "location"]]</code>',
    );
</script>

## Practicing Selecting Using Index Labels

**Instructions:**    
Running a coding exercise for the first time, could take a bit of time for everything to load. Be patient, it could take a few minutes. 

**When you see `____` in a coding exercise, replace it with what you assume to be the correct code. Run it and see if you obtain the desired output. Submit your code to validate if you were correct.**

Use the output of the following code chunk to help answer the next question.

```{pyodide}
import pandas as pd
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 25)

# The data
hockey_players = pd.read_csv('data/canucks.csv')
hockey_players
```

Let's select specific players and columns.

**Tasks:**

- Select the players `Zack MacEwan`, `Jake Virtanen` and `Jordie Benn` in that order and the columns `Height`, `Weight`, `Salary` and `Country` in that order.
- Save the new sliced dataframe as object `penalty_players`.
- Display it.

```{pyodide}
#| setup: true
#| exercise: practicing_selecting_using_index_labels
import pandas as pd
from src.utils import print_correct_msg

hockey_players = pd.read_csv('data/canucks.csv')
```

```{pyodide}
#| exercise: practicing_selecting_using_index_labels
# Select the rows and columns 
# Save the new dataframe as penalty_players
____ = ____.____[____, ____]

# Display it
____
```

```{pyodide}
#| exercise: practicing_selecting_using_index_labels
#| check: true
solution = hockey_players.loc[[10, 21, 2], ['Height', 'Weight', 'Salary', 'Country']]
assert isinstance(result, pd.DataFrame), "The result should be a dataframe."
assert solution.shape == result.shape, "You may not have selected correctly."
assert list(solution.columns) == list(result.columns), "Your columns do not seem to be correct."
assert list(solution.index) == list(result.index), "Your rows do not seem to be correct."
print_correct_msg()
```

:::: { .hint exercise="practicing_selecting_using_index_labels" }
::: { .callout-note collapse="false" }

## Hint 1

- Are you using `.loc[]`?
- Are you using the correct dataframe labels? Are you using names as your row labels?
- Did you slice both columns and rows?
- Are you using 2 sets of `[]` brackets?
- Are you using "quotations"?

:::
::::

:::: { .solution exercise="practicing_selecting_using_index_labels" }
::: { .callout-tip collapse="false" }

## Fully worked solution:

```{pyodide}
# Select the rows and columns 
# Save the new dataframe as penalty_players
penalty_players = hockey_players.loc[[10, 21, 2], ['Height', 'Weight', 'Salary', 'Country']]

# Display it
penalty_players
```

:::
::::
