---
params:
  dynamictitle: "module6_05"
title: "`r params$dynamictitle`"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
## DO NOT FORGET TO CHANGE THIS ACCORDINGLY 
library(rmarkdown)
# MAke sure you are updating your title 
knitr::opts_chunk$set(echo = TRUE,
                      base.dir = ".", 
                      base.url = "/",
                      fig.path = paste("../../static/module4/", params$dynamictitle,"/", sep = ""))

knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)

```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 350)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 15)
cereal = pd.read_csv('cereal.csv')
```


type: slides


# Function Arguments 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

When we learned functions in Module 5, arguments are something we implemented into our functions without much discussion and it's time now that we address them. 

Arguments play a paramount role when it comes to adhering to the DRY principle as well as adding flexibility to your code. 

Let's bring back the function we made named `squares_a_list()`. 


```{python}
def squares_a_list(numerical_list):
    new_squared_list = list()
    
    for number in numerical_list:
        new_squared_list.append(number ** 2)
    
    return new_squared_list
```

The reason we made this function in the first place was to DRY out our code and avoid repeating the same `for` loop for any additional list we wished to operate on. 

What happens now if we no longer wanted to square a number but calculate a specified exponential of each element, perhaps $n^3$, or $n^4$ ? Would we need a new function? 


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We could make a similar new function for cubing the numbers: 


```{python}
def cubes_a_list(numerical_list):
    new_cubed_list = list()
    
    for number in numerical_list:
        new_cubed_list.append(number ** 3)
    
    return new_cubed_list
```

But this feels repetitive. 



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

A better solution that adheres to the DRY principle is to tweak our original function but add an additional argument.       
Take a look at `exponent_a_list()` which now takes 2 arguments; the original `numerical_list`, and now a new argument named `exponent`. 

```{python}
def exponent_a_list(numerical_list, exponent):
    new_exponent_list = list()
    
    for number in numerical_list:
        new_exponent_list.append(number ** exponent)
    
    return new_exponent_list
```

```{python}
numbers = [2, 3, 5]
exponent_a_list(numbers, 3)
```

This gives us a choice of exponent. We could use the same function now for any exponent we want instead of making a new function for each. 

```{python}
exponent_a_list(numbers, 5)
```

This makes sense to do if we foresee needing this versatility, else the additional argument isn't necessary. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Default Values for Arguments 

Python allows for default values in the event that an argument is not provided to the function.           
For example, in a new version of `exponent_a_list()`, the function uses a default value of `2` for `exponent`. 

```{python}
def exponent_a_list(numerical_list, exponent=2):
    new_exponent_list = list()
    
    for number in numerical_list:
        new_exponent_list.append(number ** exponent)
    
    return new_exponent_list
```

Since we do not specify the exponent argument when we call our function, it defaults to an exponent of `2`: 

```{python}
numbers = [2, 3, 5]
exponent_a_list(numbers)
```



Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We also have the option of assigning this `exponent` argument something other than 2.  

We can specify a value for `exponent` using `exponent=5` if we need to:
```{python}
exponent_a_list(numbers, exponent=5)
```
Since exponent takes the second argument position omiting the `exponent=` part will result in the same output: 

```{python}
exponent_a_list(numbers, 5)
```


Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Functions can have any number of arguments and any number of optional arguments but we must be careful with order in which arguments are defined and called. 

When we defined our arguments in a function, all arguments with default values need to be defined ***after*** required arguments. If any required arguments follow any arguments with default values, an error will occur.     
Let's take our original function `exponent_a_list()` and re-order it so the optional `exponent` argument is defined first. We will see Python throw an error: 

```python
def exponent_a_list(exponent=2, numerical_list):
    new_exponent_list = list()
    
    for number in numerical_list:
        new_exponent_list.append(number ** exponent)
    
    return new_exponent_list
```

```out
Error: non-default argument follows default argument (<string>, line 1)
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

## Argument Ordering

Up to this point, we have been calling functions with multiple arguments in a single way. When we call our function, we have been ordering the arguments in the order the function defined them in. So, in `exponent_a_list()`, the argument `numerical_list` is defined first, followed by the argument `exponent`.

```{python}
def exponent_a_list(numerical_list, exponent=2):
    new_exponent_list = list()
    
    for number in numerical_list:
        new_exponent_list.append(number ** exponent)
    
    return new_exponent_list
```

Naturally, we have been calling our function with the arguments in this order as well: 

```{python}
exponent_a_list([2, 3, 5], 5)
```

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

We showed earlier that we could also call the function by specifying `exponent=5`:
```{python}
exponent_a_list([2, 3, 5], exponent= 5)
```

Another way of calling this would be to also specify any of the argument names that do not have default values, in this case `numerical_list`:

```{python}
exponent_a_list(numerical_list=[2, 3, 5], exponent=5)
```
What happens if we switch up the order of the arguments and put `exponent=5` followed by `numerical_list=numbers`? 

```{python}
exponent_a_list(numerical_list=[2, 3, 5], exponent=5)
```
It still works! 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

What about if we switch up the ordering of the arguments without specifying any of the argument names:

```{python eval=FALSE}
exponent_a_list(5,  [2, 3, 5])
```
```out
TypeError: 'int' object is not iterable

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "<string>", line 4, in exponent_a_list
```

Our function doesn’t recognize the input arguments and an error occurs because the two arguments are being swapped - it thinks 5 is the list and [2, 3, 5] is the exponent. 

It's important to take care when ordering and calling a function.

The rule of thumb to remember is if you are going to call a function where the arguments are in a different order from how they were defined, you need to assign the argument name to the value when you call the function. 

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s practice what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
