---
format: revealjs
title: What did we learn and what to expect in assignment 1
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```

## Summary  

Students are now expected to be able to:

- Describe the components of a Dataframe.
- Read a standard `.csv` file using Pandas `pd.read_csv()`.
- Load the `pandas` library into Python.
- Demonstrate indexing and slicing with `.loc[]` and `.iloc[]`.
- Demonstrate Selecting columns of a dataframe using `df[]` notation.
- Obtain values from a dataframe using `.loc[]`.
- Sort a dataframe using `.sort_values()`.
- Create simple summary statistics using `.describe()`.
- Construct simple visualizations using Altair.
- Create a `.csv` file from a dataframe using `.to_csv()`.


---

## Assignment Instructions

The assignment will concentrate not only on the learning objectives above but also

- Navigating a Jupyter Notebook
- Understanding cells
- Creating Markdown cells and coding cells


---

## Attribution

The cereal dataset:

 “[80 Cereals](https://www.kaggle.com/crawford/80-cereals/)” (c) by [Chris Crawford](https://www.linkedin.com/in/crawforc3/) is licensed
under [Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/)



# On to Assignment 1!