---
title: "module1_29"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 8)
cereal = pd.read_csv('cereal.csv')
cereal2 = pd.read_csv('candybars.csv')
cereal_mini = cereal2.head(7).loc[:, ['name', 'weight', 'available_canada_america' ]]
```


type: slides

# Frequency Tables and Writing CSVs 

Notes: <br>

---

## What is Frequency?

_*Frequency*_: The number of times a value occurs within the data. 

```{python}
cereal_mini
```

## What is a Frequency Table?

```{python echo=FALSE}

cereal_mini['available_canada_america'].value_counts()
```
Notes: 

Before we explain what a frequency table is, you must know what frequency means first. 

_*Frequency*_ is simply put, the number of times a value occurs within the data. For example, let's say we have a sample of our candybars data. 
For example, let's say we have a sample of our candybars data. 

If we count the number of times the value `Both` appears in the `available_canada_america` column, we get 3 times. This is the frequency of the value `both`.  

A frequency table is a manner of displaying all the possible values of a column in our data and the number of occurrences (frequencies) of each value. 

For our sample data, a frequency table for the `available_canada_america` column would look like this: 

---



```{python}
mfr_column = cereal['mfr']
mfr_column
```

```{python}
mfr_freq = mfr_column.value_counts()
mfr_freq
```


Notes: 

If we want to get a frequency table of a categorical column, there are a few steps that need to be followed. 

Up until now,  we discussed getting a single column from a dataframe using double brackets - `df[['column name']]`. 

For frequency tables, however, we only use single brackets to obtain the column values.

We saved the object in a variable called `manufacturer_column` in the same way we have saved objects before.   

Next we can use `.value_counts()` referencing that the column we saved as `manufacturer_column`.  

This let's us see the frequency of each categorical value.


---


```{python}
mfr_col_wrong = cereal[['mfr']]
mfr_col_wrong
```


```python
mfr_col_wrong.value_counts()
```

```out
AttributeError: 'DataFrame' object has no attribute 'value_counts'

Detailed traceback: 
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
```

Notes: 

If we used double square brackets with `pd.value_counts()` we would get an error that looks like this so it's important to take care with using the correct number of square brackets.

---

## Saving a dataframe

```{python}
mfr_freq.to_csv('mfr_frequency.csv', index=False)
```


Notes: 

Sometimes it's useful to save a new dataframe as a `csv` file for future use or to use in another application.

We can save dataframes using the method `.to_csv()`. 

We put our desired `csv` file name in quotations within the parentheses and follow it with the argument `index=False` so we don't export our index column which is just a column of numbers.  

---

# Let’s apply what we learned!

Notes: 

 <br>