---
title: "module1_26"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 16)
cereal = pd.read_csv('cereal.csv')
```


type: slides

# Summary Statistics

Notes: 

<br>

---

```{python}
cereal = pd.read_csv('cereal.csv')
cereal.head(15)
```

Notes: 

Now we've learned about how to get the data in to the shape and size that we desire, now we ca have some fun with it!


We usually like to learn from it. One place we can start is summary statistics, so we can calculate interesting values for each of the variables or columns in our dataframe. 

Let's start by doing this for the cereal dataset again.

---

## Numerical and Categorical Columns 


### Categorical data

Consists of qualitative observations such as characteristics - things generally containing words. 

**Examples**      

- Colours
- Names 

<br>

### Numerical data

These data are usually expressed with numbers. 

**Examples**    

- Measurements
- Quantities


Notes: 

Before we go further, let's quickly discuss the 2 different types of data.  

Categorical data consists of qualitative observations such as characteristics - things generally containing names or words. Examples would be colours or names of things.

Numerical data are usually expressed with numbers such as measurements or quantities.


Our columns in our dataframe are considered one of the two of these.

---

## Pandas describe()


```{python}
cereal.describe()
```


Notes:

Pandas has a lot up its sleeve but one of the most useful methods is called `.describe()` and it does exactly that. it _describes_ our data.  

Let's try it out on our cereal dataset.

By default `df.describe()` only shows numerical columns.

---

```{python}
cereal.describe()
```


- `count`: The number of non-NA/null observations.
- `mean`: The mean of  column 
- `std` : The standard deviation of a column
- `min`: The min value for a column
- `max`: The max value for a column 
- By default the 25, 50 and 75 percentile of the observations

Notes:

Let's talk a little bit about the output of `.describe()`.

On the left-hand side we see a new column. This column contains the names of the different summary statistics that `.describes()` gives us back for our dataset. Let's talk about them each individually: 

- `count`: The number of non-NA/null observations.
- `mean`: The mean of the column 
- `std` : The standard deviation of a column
- `min`: The min value for a column
- `max`: The max value for a column 
- By default the 25, 50 and 75 percentile of the observations are also included. 

---

```{python}
cereal.describe(include='all')
```

- `unique`: how many observations are unique
- `top`: which observation value is most occurring
- `freq`: what is the frequency of the most occurring observation 

Notes: 

We can make changes to either limit how much is shown or include more using describe.  One useful argument is `include` and a value we can give to that is `all`.

This expands the output so we get summary statistics for both categorical and numerical columns now. 

Adding `include='all'` within the brackets adds some additional statistics about categorical columns including:

- `unique`: which indicates the number of unique observations
- `top`: which tells up the observation value that is most occurring
- `freq`: which informs us of the frequency of the most occurring observation

---

```{python}
ratings = cereal[['rating']]
ratings.mean()
```


```{python}
ratings.sum()
```


```{python}
ratings.median()
```

Notes: 

We can also get single statistics of each column using functions like:
`.mean()`,`.std()`, `.count()`, `.median()`, `.sum()`. 

To do this, we first have to grab the column that we are interested in exploring, and then we add the verb.

Here are some examples of things that we can calculate. First we calculate the mean of the ratings, then we calculate sum of the ratings, and finally the median of the ratings. 

---

```{python}
cereal.mean()
```

Notes: 

We can also use these summary statistic verbs on the entire dataframe. This now shows the mean value of each column in the dataframe. 

You'll notice that only the numerical variables are calculated which makes sense since we would not be able to calculate the mean of categorical data. 

---

# Let’s apply what we learned!

Notes:

<br>
