---
title: "module1_11"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
cereal = pd.read_csv('cereal.csv')
```

type: slides

# Slicing columns using .loc[]


Notes: 

<br>

---


```{python}
cereal.loc[:, 'calories':'fiber']
```


Notes: 

What happens now if we wanted all the rows of the dataframe but only the columns `calories` to `fiber`?

We can use `:` to indicate from "end" to "end" for our rows rows:

---

## So Far
    
- `.loc[]` is used to slice columns and rows by **label** and within an interval.

- We always specify **row** indexing first, then **columns**.
  
 ```python
cereal.loc['row name start':'row name end', 'column name start':'column name end']
```
  
- If we aren’t slicing any columns, but we are slicing rows  we can shorten that to
```python
df.loc[ 'row name start':'row name end']
```

- However, the reverse is not true. If we want all the rows with only specific columns, we specify we want all the row first with just a colon `:` followed by interval of the columns:

```python
df.loc[:, 'column name start':'column name end']
```
- We can read `:` as **"to"**.

- If the indices are labelled with numbers, we do not need "quotations" when calling them.
  
Notes:

- `.loc[]` is used to slice columns and rows by **label** and within an interval.

- We always specify **row** indexing first, then **columns**.

- If we aren’t slicing any columns, but we are slicing rows we only need to specify the row labels.

- However, the reverse is not true. If we want all the rows with only specific columns, we specify rows first and therefore we would need to make it clear with a colon first that we are slicing all the rows followed by the column labels. 

- We can read `:` as **"to"**.

- And finally, if the indices are labelled with numbers, we do not need "quotations" when calling them.

    
---
    
# Let’s apply what we learned!
    
Notes:

<br>

    