---
title: "module1_20"
output:
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                            
opts_chunk = NULL,
                            
knit_hooks = NULL,
                            
opts_hooks = NULL,
                            
opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
             
base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
pd.set_option('display.max_rows', 12)
```


type: slides

# Slicing and selecting using .iloc[]


Notes: <br>

---

## Slicing Dataframe


```{python}
cereal = pd.read_csv('cereal.csv')
cereal.head(10)
```


Notes: 

Up to this point, we have been manipulating our dataframe with column and row _**labels**_  using `.loc[]`.   

Slicing can also be done by the location position of each row with `.iloc[]`.

`.iloc[]` is very similar, however, the "i" in `iloc` refers to the index _**integer**_ position.    

We are going to return to our cereal dataset and take a look at the first 10 rows.

Let's say we want the rows `All-Bran` to `Apple Cinnamon Cheerios` but we want to slice based on their position.  

Using Python's counting method of starting at zero, we conclude `All-Bran` to be at position to 2.

We get `Apple Cinnamon Cheerios` position to be 5 in the same way.

We are lucky with this dataframe because our index labels match the position of the rows. 

---

 
```{python}
cereal.loc[2:5]
```
 

```{python}
cereal.iloc[2:5]
```



Notes: 

We can use the same coding structure we learned with `.loc[]` but this time using row positions instead of labels with `.iloc[]`.

But wait! Something is missing here!

Why doesn't `Apple Cinnamon Cheerios` appear in the dataframe? 

---

```{python}
cereal.iloc[2:6]
```


Notes: 

That's because when we use slicing by index position, it will take all the indices including the lower bound but _EXCLUDING_ the upper bound. 

If we wanted to include `Apple Cinnamon Cheerios` we would have to go 1 index position further. 

If we think about this a bit it actually make some sense. Think about the calculation `6 - 2 = 4` . We get 4 items remaining which is the amount of cereals we want in our in new dataframe. 

---
```{python echo=FALSE}
cereal.head()
```



```{python}
cereal.iloc[:, 0:6]
```


Notes: 

The same concept can be applied to the columns of the dataframe. 

Let's say we want all the rows but we only want the columns starting at `name` and ending (and including) at column `fat`.     
Using the logic we learned in the last set of slides, we would use the following code:


We would need to specify all rows using ` : ` as we did when we used `.loc[]`. 

The column `name` is at index position 0 (we do not include the index label as a column) and `fat` is at index position 5. 

Since we want to include the 5th column we need to use the 6th position to make sure we get all the columns _BEFORE_ the upper bound.




---

 Let’s say we want the rows `All-Bran` to `Apple Cinnamon Cheerios` and `name` to `fat`.  
 
#### Rows

**Lower Bound**: `All-Bran` located at position 2.     
**Upper Bound**:`Apple Cinnamon Cheerios` is located at position 5.  


#### Columns 

**Lower Bound**: `name` is located at position 0.     
**Upper Bound**:`fat` is located at position 5.

```{python}
cereal.iloc[2:6, 0:6]
```


Notes: 


 Let’s say we want the rows `All-Bran` to `Apple Cinnamon Cheerios` and `protein` to `fat`.  
 
For rows, the lower bound `All-Bran` is located at position 2 and the upper bound `Apple Cinnamon Cheerios` is located at position 5.  


Now the column's lower bound  `name` is located at position 0 and the upper bound `fat` is located at position 5.

The same would apply if we only wanted certain rows with certain columns.

Both of our upper bound have been compensated with + 1 to make sure they are included in the new dataframe.

---

```{python}
cereal.head(3)
```


```{python}
cereal.iloc[0:3]
```


```{python}
cereal.iloc[:3]
```

Notes: 

There are multiple different way of writing code when you are selecting items from the beginning or end of your data.

Perhaps you only want the first 3 rows of your data.

We can use `.head(3)` or we can use `.iloc()`. 

Since we are indicating the beginning of the dataframe, we can omit the upper bound `0` just like we did we we learned slicing with `.loc[]`.

---

```{python}
cereal.iloc[74:77]
```



```{python}
cereal.iloc[-3:]
```

Notes: 

The same logic can be applied for end of a dataframe. This time we want the last 3 rows. 

Since this dataframe has 76 rows we could use our lower bound as 74 and upper bound as 77 (76 +1). 

A better and easier way to write this, where you don't even need to know the number of rows in the dataframe would be to specify you are counting your rows from the bottom with a negative in front of the number of rows you want. 

This example takes the first 3 rows of the **bottom** of the dataframe.  since we are collecting data to the end of the dataframe, we do not need to include the ending row index number. 



---

## Selecting with .iloc[]

```{python }
cereal.head(10)
```

<div> 
<table id="**Rows**" style="width:50%; float:left"> 
	<tr> 
		<td>
|**Row**|**Row Position**|
|--|--|
|`Almond Delight`| Position 4|
|`Basic 4`| Position 7 |
|`Apple Jacks`|  Position 6 |
</td> 
</tr> 
</table> 
<table id="**Columns**" style="width:50%; float:left"> 
	<tr> 
		<td>
|**Columns**|**Column Position**|
|-------|----------------|
| `name` | Position 0
| `calories` |Position 3|
| `fat` | Position 5 |
|`type` |  Position 2|
</td> 
	</tr> 
</table>  
</div> 

Notes: 

Selecting using `iloc` is done identically to `loc`, however, the items within each set of square brackets **MUST** be integers, and not in quotation marks.

Let’s say we want the rows `Almond Delight`, `Basic 4` and `Apple Jacks`  with the columns `name`, `calories`, `fat` and `type` _in that order_.

---

<table id="**Rows**" style="width:50%; float:left"> 
	<tr> 
		<td>
|**Row**|**Row Position**|
|--|--|
|`Almond Delight`| Position 4|
|`Basic 4`| Position 7 |
|`Apple Jacks`|  Position 6 |
</td> 
</tr> 
</table> 
<table id="**Columns**" style="width:50%; float:left"> 
	<tr> 
		<td>
|**Columns**|**Column Position**|
|-------|----------------|
| `name` | Position 0
| `calories` |Position 3|
| `fat` | Position 5 |
|`type` |  Position 2|
</td> 
	</tr> 
</table>  

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


```{python}
cereal.iloc[[4, 7, 6], [0, 3, 5, 2]]
```


Notes: 

`Almond Delight ` takes row position 4, `Basic 4`	takes row position 7 and `Apple Jacks` is located at position 6. The desired columns `name`, `calories`, `fat`, and `type` take column index positions 0,5,3, and 2 respectively.  

Now let's put those position into square backing within `df.iloc[]`.


---

# Nice work! Let’s apply what we learned!

Notes: 

<br>