---
title: "Module1_07"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
```

type: slides

# Slicing with Pandas using .loc[]

Notes: Script here.
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Congratulations on writing your first code! This is great! We have read in our data and know the dimensions. What now? Let's go over how we would **index**, **slice** and  **select** certain columns or rows of our data.


Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

## Cereal Data

Let's import pandas and bring in a dataset named `cereal.csv`.

Attribution:     
_“[80 Cereals](https://www.kaggle.com/crawford/80-cereals/)” (c) by [Chris Crawford](https://www.linkedin.com/in/crawforc3/) is licensed under [Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/)_

```{python }
import pandas as pd
  
df = pd.read_csv('cereal.csv')
df.head()
```

  
Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>
    
---

## The Index
    
We can see all the columns and the first 5 rows of the dataframe.
Let's say we only want certain rows of the whole dataframe or certain columns.

We talked about how `.head()` will generate the first few rows (5 as default) of a dataframe but what if we wanted rows 5-10?

The first column of this dataframe is called the `index`. Each row has a label (the index) as well as a position. In this case, the index label of an observation is the same as it's position. This doesn't always have to be the case. We can assign columns as the index, but we will discuss this in the next section. 

Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

Here are the first 10 rows of the dataframe: 

```{python}
df.head(10)
```

Let's talk about observation 4 named `Almond Delight`.  Its index label is `4` as well as it's index position.    
If you just went and counted those again and started screaming "5! It's the fifth position", that's ok. In the Python language, we start counting at position 0 (then 1, 2, 3, and 4 for Almond Delight).
  
Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

So now let's say we want the 5 rows past `Almond Delight`. That means we want rows `Apple Cinnamon Cheerios` to `Cap'n'Crunch`.    
The following code cuts the dataframe from  "Apple Cinnamon Cheerios" to "Cap'n'Crunch" keeping all the columns:

```{python}
df.loc[5:10]
```

```python
df.loc[5:10]
```

This essentially means to  _"Obtain the values in the dataframe located from `5` to `10`."_       
      
Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3"/>
</audio></html>

---

What if we only wanted certain columns now?

Perhaps we were only interested in the `calories` to `fiber` columns of the "Apple Cinnamon Cheerios" to "Cap'n'Crunch" rows?
We put our desired rows first, then columns and separate them with a comma.  


```{python}
df.loc[5:10, 'calories':'fiber']
```

`loc` is used to slice columns and rows by **label** and within an interval.

The general format to slice both rows and columns together looks like this:

```python
`df.loc['row name start':'row name end', 'column name start':'column name end']`
```


Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

There is a handy shortcut for slices where you want the begining of a dataframe to a specified row or column label or a specified row or column label to the end of a dataframe. 

For example if we want all the rows up to "Apple Jacks" which has a label equal to 6, we could omit the first label in the code all together: 

```{python}
df.loc[:6]
```

We can do something similar for the end of a dataframe. Let's say now we want the first 6 rows and only the columns from 'sugars' onwards. we would omit the ending label this time:

```{python}
df.loc[:6, 'sugars':]
```


Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s try it out!
    
Notes: Script here
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>
    