---
title: "module1_13"
author: "Hayley Boyce"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
df = pd.read_csv('cereal.csv')
```

type: slides

# Selecting using .loc[]

Notes: Script here.
<html>
<audio controls >
<source src="/placeholder_audio.mp3" />
</audio></html>

---

## Unordered Indexing

We have our trusty `cereal.csv` data once again.


```{python echo = FALSE}
df
```


What would we do if we want to select columns and rows that don't fall consecutively or if we want to rearrange them?


Notes: Script here.
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

Let's say we wanted only the rows labeled `Clusters` (13), `Trix` (73) and `Wheaties` (75) and the columns `name`, `type`, `sugars` and `rating`.
How would we obtain them now?

We need to specify each column and row label that we want between square brackets `[]`, separated with commas:


```{python}
df.loc[[13,73,75], ['name', 'type', 'sugars', 'rating']]
```


We can also reorder the entries to change the column and row order.

Notes: Script here.
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

What if we wanted the rows to be in the order `Wheaties`, `Trix` and `Clusters` and columns in the order `name`, `type`, `rating` and `sugars`
How would we obtain that?    
It's as simple as rearranging the order you target your rows and columns:

```{python}
df.loc[[75, 73, 13], ['name', 'type', 'rating', 'sugars']]
```


Notes: Script here.
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>

---

# Let’s apply what we learned!

Notes: Script here
<html>
<audio controls >
  <source src="/placeholder_audio.mp3" />
</audio></html>