---
title: "module1_18"
author: "Hayley Boyce"
output: 
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)
knitr_opts <- knitr_options( opts_knit = NULL,
                             opts_chunk = NULL,
                             knit_hooks = NULL,
                             opts_hooks = NULL,
                             opts_template = NULL)
md_document_custom <- md_document(variant = "gfm")
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = md_document_custom)
library(reticulate)
```


```{python include=FALSE}
import pandas as pd
import numpy as np
pd.set_option('display.width', 400)

np.set_printoptions(linewidth=400)

pd.set_option('display.max_columns', 15)
cereal = pd.read_csv('cereal.csv')
```


type: slides


# Selecting a Single Column

---

```python
df.loc[:, ['column name']]
```
<br>

```{python}
cereal.loc[:, ['type']]
```

Notes: 

Something we often do in data analysis is obtaining a single column from a dataframe.
We can again use `.loc[]` to do this which would look something like this:

`dataframe.loc[:, ['column name']]` 

So if we wanted the column named `type` from our cereal dataframe we could use the syntax: 

`cereal.loc[:, ['type']]` 

This seems a bit long winded and since we do this type of thing often pandas has provided a quicker syntax to use to do the same thing. 

---

``` Python
df[['column name']]
```

<br>


```{python}
cereal[['type']]
```

Notes:

Instead we can selecting a single column can be done without using `.loc[]` and we can just specify the dataframe name, followed by double square brackets containing the column of interest.

That makes the syntax for selecting the column `type` from the `cereal` dataframe: 

```python
cereal[['type']]
```

---

# Let’s apply what we learned!

Notes: <br>