---
format: revealjs
title: Python Operations
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```

  
| Operator | Description |  
| :---:|:---:|  
| `+` | addition |  
| `-` | subtraction |  
| `*` | multiplication |  
| `/` | division |  
| `**` | exponentiation |   


:::{.notes} 
We have already seen a few of Python's arithmetic operators, but there are a few on this list that may be new to you.
:::

---

## Numeric Operations 

```{python}
6 + 5.7
```

<br>

```{python}
15 - 7
```

<br>

```{python}
4.5 * 4
```

<br>

```{python}
2 ** 3
```

<br>

```{python}
2.2 ** 5
```


:::{.notes} 
Let's apply these to the Python types we have learned and observe the results.

These operators act as expected on numeric types.

An `int` plus a `float` results in a `float`. 

And the subtraction of 2 values of type `int` results with a type `int`.

Multiplication with a `float` and an `int` will result in a `float` as well. 

Exponents can be calculated with `**` and applied with `int` as well as `float` data types.
:::

---

## Bool

```{python}
True + True 
```

<br>

```{python}
True * 4
```

<br>

```{python}
False * 2 + True
```

<br>

```{python}
False + 4
```


:::{.notes} 
We saw that addition, subtraction, multiplication, and exponential operations work as expected with numeric values but let's check out what happens with the other data types. 

What happens when we try to add up `bool` values? 

We see that `True` values are cast as a value of `1`, and `False` values are cast as `0` when they are added together.
:::

---

## Str

```{python}
'The monster under my bed' + ' is named Mike' 
```

<br>

```python
'The monster under my bed' - ' is named Mike' 
```

```out
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Detailed traceback: 
  File "<string>", line 1, in <module>
```

<br>

```python 
'The monster under my bed' / ' is named Mike' 
```

```out
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Detailed traceback: 
  File "<string>", line 1, in <module>
```


:::{.notes} 
Strings react rather interestingly with the addition operator.  

For instance, when we add strings, we add the sequence from one end to the other. This is also called concatenation. 

And we cannot multiply, divide or subtract two strings.
:::

---

```python
'The monster under my bed' + 1200
```

```out
TypeError: can only concatenate str (not "int") to str

Detailed traceback: 
  File "<string>", line 1, in <module>
```

<br>

```{python}
'The monster under my bed' + str(1200)
```

<br>

```{python}
'The monster under my bed' * 3
```


:::{.notes} 
We saw that we can operate on `float` and `int` values together, but what about `str` and numeric values? 

Adding a string to an integer does not work unless we first cast the integer to a string.

What about the multiplication of a string by an integer? 

This will repeat the string by the number you are multiplying. 

In this case, the string `'The monster under my bed'` is repeated 3 times. 

We can multiply strings, and it concatenates the strings together! Since we multiplied by 3, the string is repeated 3 times.
:::

---

## List 

```{python}
list1 = [1, 2.0, 3, 4.5] + ['nine', 'ten', 'eleven', 'twelve']
list1
```

<br>

```python
[1, 2.0, 3, 4.5] - [3, 5, 2, 1]
```

```out
TypeError: unsupported operand type(s) for -: 'list' and 'list'

Detailed traceback: 
  File "<string>", line 1, in <module>
```

<br>

```{python}
# | error: true
[1, 2.0, 3, 4.5] * [5, 6, 7, 8]
```


:::{.notes} 
How about with other data types like **lists**, **tuples** and **dictionaries**?

If we add lists, similarly to strings, the lists concatenate together to create a single list containing the elements of both lists. 

Other operators, like subtraction and multiplication, are not supported when working with lists.
:::

---

## Boolean Operators

|Operator    |Description|
|:------:|:--------------|
|`x == y`|    is x equal to y?|
|`x != y`|    is x not equal to y?|
|`x > y` |    is x greater than y?|
|`x >= y`|    is x greater than or equal to y?|
|`x < y` |    is x less than y?|
|`x <= y`|    is x less than or equal to y?|
|`x is y`|    is x the same object as y?|
|`x and y` |     are x and y both true? |
|`x or y`    | is at least one of x and y true?|
|`not x`    | is x false?|


:::{.notes} 
When we've filtered our data, we've seen different Boolean operators, but we have some new ones here for you.

Let's explore them.
:::

---

```{python}
'dogs' == 'cats'
```

<br>

```{python}
6 < 7
```

<br>

```{python}
(6 < 7) and ('dogs' == 'cats')
```

<br>

```{python}
(6 < 7) or ('dogs' == 'cats')
```


:::{.notes} 
Let's start with 2 base statements; 

- dogs and cats are not equal, so we get a False and
- 6 < 7 is True

We can combine them to explore the `and`, `or` and `not` operators. 

We can check if both statements are `True` using the keyword `and`. 

In this case, since both statements are not `True`, combining them with `and` will evaluate to `False`. 

On the other hand, the `or` operator checks if at least one of the statements are `True` and since `6 < 7`  is a `True` statement,  the `or` statement evaluates to `True`.

Since one statement is true, the combined "or" statement is True.
:::

---

```{python}
not ('dogs' == 'cats')
```

<br>

```{python}
not  (6 < 7)
```


:::{.notes} 
We know that `('dogs' == 'cats') ` is `False`, so a `not` operator gives us a `True` because it inverts the Boolean value. 

While we know `(6 < 7)` is `True` the statement  `not  (6 < 7)` produces a `False`.

How can we translate all this to dataframes now?

Have you ever wondered why we can do summary statistics on some columns and not others? We are going to explore this in the next section. 

Seeing if the statement is False will result in a `False` output since `(6 < 7)` is True. 
:::



# Let’s apply what we learned!