---
format: revealjs
title: What Did we Learn and What to Expect in Assignment 7
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```


## Summary  

Students are now expected to be able to:

- Describe what Python libraries are, as well as explain when and why they are useful.
- Identify where code can be improved concerning variable names, magic numbers, comments and whitespace.
- Write code that is human readable and follows the black style guide.
- Import files from other directories.
- Use `pytest` to check a function's tests.
- When running `pytest`, explain how pytest finds the associated test functions.
- Explain how the Python debugger can help rectify your code.


:::{.notes}
The assignment will concentrate on the learning objectives as well as building knowledge on existing concepts. 
:::

---

## Attribution

The cereal dataset:

 “[80 Cereals](https://www.kaggle.com/crawford/80-cereals/)” (c) by [Chris Crawford](https://www.linkedin.com/in/crawforc3/) is licensed
under [Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0/)



# On to Assignment 7!